/**
 * Area 2 — Locator Quality Assessment
 *
 * Tests that extractCandidatesFromIdentity + rankLocatorCandidates produce
 * robust, readable, and unique locators on realistic DOM structures.
 *
 * Each test constructs an ElementIdentity that mimics a real-world DOM
 * structure and verifies the ranking output.
 *
 * Architecture: .drytis/EXPANDED_VALIDATION_DESIGN.md §4
 */

import { describe, it, expect } from 'vitest';
import {
  extractCandidatesFromIdentity,
  rankLocatorCandidates,
  isAutoGeneratedId,
  isCssInJsClass,
  LocatorCategory,
} from '../../src/domain/locator-ranking';
import type { ElementIdentity } from '../../src/shared/types';
import { LocatorStrategyType } from '../../src/domain/enums';
import type { RawObservation } from './types';

// ── Helpers ──────────────────────────────────────────────────────────

function makeIdentity(overrides: Partial<ElementIdentity> = {}): ElementIdentity {
  return {
    elementId: 'test-elem-1',
    accessibleName: '',
    ariaRole: null,
    ariaLabel: null,
    ariaLabelledBy: null,
    placeholder: null,
    tag: 'DIV',
    className: null,
    name: null,
    stableId: null,
    testId: null,
    dataCy: null,
    dataQa: null,
    cssSelector: 'body > div',
    xPath: '/html/body/div',
    inIframe: false,
    shadowDom: false,
    ...overrides,
  };
}

function assessLocator(identity: ElementIdentity) {
  const candidates = extractCandidatesFromIdentity(identity);
  const ranked = rankLocatorCandidates(candidates);
  const top = ranked[0] ?? null;
  return { candidates, ranked, top };
}

// ── Raw Observations ─────────────────────────────────────────────────

const observations: RawObservation[] = [];

function recordObs(
  observationId: string,
  scores: RawObservation['scores'],
  observed: string,
  rootCause: string,
  category: RawObservation['category'],
  severity: RawObservation['severity'],
  subsystem: RawObservation['subsystem'],
): void {
  observations.push({
    observationId,
    area: 'locator',
    capabilityId: 'locator-quality',
    framework: null,
    scores,
    support: scores.q3_locator >= 4 ? 'full' : scores.q3_locator >= 2 ? 'partial' : 'unsupported',
    observed,
    rootCause,
    category,
    severity,
    subsystem,
    confidence: 'VERIFIED',
  });
}

// ── Tests ────────────────────────────────────────────────────────────

describe('Locator Quality Assessment', () => {

  describe('LQ-01: testId is top-ranked locator', () => {
    it('produces TEST_ID strategy at highest confidence', () => {
      const identity = makeIdentity({
        testId: 'submit-btn',
        ariaLabel: 'Submit',
        accessibleName: 'Submit',
        tag: 'BUTTON',
        cssSelector: 'body > form > button',
      });
      const { top } = assessLocator(identity);

      expect(top).not.toBeNull();
      expect(top!.type).toBe(LocatorStrategyType.TEST_ID);
      expect(top!.priority).toBe(1);
      // testId:primary has 0.95 confidence override
      expect(top!.confidence).toBeGreaterThanOrEqual(0.90);

      recordObs('LQ-01',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 5, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
        `testId correctly ranked #1`, 'None',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-02: React auto-generated ID filtered', () => {
    it('rejects :r5: style ID and uses ariaLabel', () => {
      const identity = makeIdentity({
        stableId: ':r5:',
        ariaLabel: 'Search products',
        tag: 'INPUT',
        cssSelector: 'body > input',
      });
      const { top, ranked } = assessLocator(identity);

      expect(isAutoGeneratedId(':r5:')).toBe(true);
      expect(top).not.toBeNull();
      expect(top!.type).not.toBe(LocatorStrategyType.STABLE_ID);

      recordObs('LQ-02',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `React auto-generated ID correctly filtered, ariaLabel used instead`, 'None',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-03: CSS-in-JS class filtered', () => {
    it('rejects Emotion css-1abcde class', () => {
      const identity = makeIdentity({
        className: 'css-1abcde other-class',
        accessibleName: 'Submit',
        tag: 'BUTTON',
        // CSS selector containing CSS-in-JS class pattern
        cssSelector: 'body > button.css-1abcde',
      });
      const { top } = assessLocator(identity);

      // isCssInJsClass checks CSS selectors for the dot-prefixed pattern
      expect(isCssInJsClass('.css-1abcde')).toBe(true);
      expect(top).not.toBeNull();
      // CSS-in-JS selector is filtered out, falls back to content-based accessibleName
      expect(top!.type).not.toBe(LocatorStrategyType.CSS);

      recordObs('LQ-03',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `CSS-in-JS class filtered, accessibleName used`, 'None',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-04: No-semantic element falls back to structural', () => {
    it('produces CSS or XPATH locator for bare div', () => {
      const identity = makeIdentity({
        tag: 'DIV',
        cssSelector: 'body > div.container > div.content > div.item',
        xPath: '/html/body/div[1]/div[2]/div[3]',
      });
      const { top, ranked } = assessLocator(identity);

      expect(ranked.length).toBeGreaterThan(0);
      // Structural candidates: CSS ranked before XPath (higher confidence)
      expect(top!.type === LocatorStrategyType.CSS || top!.type === LocatorStrategyType.XPATH).toBe(true);
      // Confidence for structural is low (0.30–0.40)
      expect(top!.confidence).toBeLessThanOrEqual(0.40);

      recordObs('LQ-04',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 4, q4_description: 3, q5_replay: 3, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `Structural fallback (CSS/XPath) used for element with no semantic attributes`,
        'No semantic attributes on element — structural fallback is by design',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-05: ariaLabel is high-priority locator', () => {
    it('produces role-based or accessibleName locator from ariaLabel', () => {
      const identity = makeIdentity({
        ariaLabel: 'Close dialog',
        ariaRole: 'button',
        tag: 'BUTTON',
        cssSelector: 'body > div > button',
      });
      const { top } = assessLocator(identity);

      expect(top).not.toBeNull();
      // With ariaRole + ariaLabel, produces role locator; otherwise accessibleName
      expect(top!.type === LocatorStrategyType.ROLE || top!.type === LocatorStrategyType.ACCESSIBLE_NAME).toBe(true);
      // Accessibility category is second highest priority
      expect(top!.priority).toBe(1);
      expect(top!.confidence).toBeGreaterThanOrEqual(0.80);

      recordObs('LQ-05',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 5, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
        `ariaLabel used as primary locator when present`, 'None',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-06: accessibleName fallback when no testId/ariaLabel', () => {
    it('uses accessibleName-based locator', () => {
      const identity = makeIdentity({
        accessibleName: 'Email address',
        tag: 'INPUT',
        cssSelector: 'body > form > input',
      });
      const { top } = assessLocator(identity);

      expect(top).not.toBeNull();

      recordObs('LQ-06',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 5, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
        `accessibleName used when no testId or ariaLabel`, 'None',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-07: Multiple strategies ranked in correct order', () => {
    it('ranks testId > ariaLabel > accessibleName > CSS', () => {
      const identity = makeIdentity({
        testId: 'login-btn',
        ariaLabel: 'Login',
        accessibleName: 'Login to your account',
        tag: 'BUTTON',
        className: 'btn btn-primary',
        cssSelector: 'body > div > form > button',
      });
      const { ranked } = assessLocator(identity);

      expect(ranked.length).toBeGreaterThanOrEqual(2);
      expect(ranked[0]!.type).toBe(LocatorStrategyType.TEST_ID);

      recordObs('LQ-07',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 4, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
        `Multiple strategies ranked correctly (testId > ariaLabel > accessibleName > CSS)`, 'None',
        'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-08: Dynamic aria-label content not detected as unstable', () => {
    it('accepts ariaLabel with timestamp content', () => {
      const identity = makeIdentity({
        ariaLabel: 'Item 5 of 12 at 3:42pm',
        tag: 'DIV',
        cssSelector: 'body > div',
      });
      const { top } = assessLocator(identity);

      // The locator system does NOT detect dynamic content in aria-label.
      // This will produce a brittle locator.
      expect(top).not.toBeNull();

      recordObs('LQ-08',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 4, q4_description: 4, q5_replay: 3, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `Dynamic aria-label content (timestamp) not detected as unstable`,
        'No pattern detection for dynamic content in aria-label values',
        'implementation-gap', 'P2', 'Locator Ranking');
    });
  });

  describe('LQ-09: Duplicate testId has no uniqueness awareness', () => {
    it('produces same locator for two elements with same testId', () => {
      const identity1 = makeIdentity({ testId: 'save-btn', tag: 'BUTTON', cssSelector: 'body > form > button' });
      const identity2 = makeIdentity({ testId: 'save-btn', tag: 'BUTTON', cssSelector: 'body > div > button' });

      const { top: top1 } = assessLocator(identity1);
      const { top: top2 } = assessLocator(identity2);

      // Both produce the same locator value — no disambiguation
      expect(top1!.value).toBe(top2!.value);

      recordObs('LQ-09',
        { q1_intent: 5, q2_abstraction: 5, q3_locator: 4, q4_description: 4, q5_replay: 3, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `Duplicate testId has no uniqueness awareness`,
        'No duplicate detection or disambiguation for testId values',
        'implementation-gap', 'P2', 'Locator Ranking');
    });
  });

  describe('LQ-10: SVG icons lack semantic anchors', () => {
    it('falls back to structural locators for SVG elements', () => {
      const identity = makeIdentity({
        tag: 'SVG',
        ariaRole: 'img',
        className: 'icon icon-close',
        cssSelector: 'body > div > svg',
        xPath: '/html/body/div/svg',
      });
      const { top } = assessLocator(identity);

      expect(top).not.toBeNull();

      recordObs('LQ-10',
        { q1_intent: 4, q2_abstraction: 4, q3_locator: 3, q4_description: 3, q5_replay: 3, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `SVG icons lack semantic anchors — fall back to structural locators`,
        'SVG elements rarely have aria-label or testId',
        'implementation-gap', 'P2', 'Locator Ranking');
    });
  });

  // ── Summary ────────────────────────────────────────────────────────

  describe('Locator Quality Summary', () => {
    it('records all locator observations', () => {
      console.log(`\n[Locator Quality] ${observations.length} observations recorded`);
      for (const obs of observations) {
        const avg = (
          obs.scores.q1_intent + obs.scores.q2_abstraction + obs.scores.q3_locator +
          obs.scores.q4_description + obs.scores.q5_replay + obs.scores.q6_confidence +
          obs.scores.q7_evidence + obs.scores.q8_assertion
        ) / 8;
        console.log(
          `  ${obs.observationId}: Q3=${obs.scores.q3_locator} avg=${avg.toFixed(1)} | ${obs.severity} | ${obs.observed}`
        );
      }
      expect(observations.length).toBeGreaterThanOrEqual(10);
    });
  });
});
