/**
 * Area 2 — Locator Quality Assessment
 *
 * Tests that extractCandidatesFromIdentity + rankLocatorCandidates produce
 * robust, readable, and unique locators on realistic DOM structures.
 *
 * Each test constructs an ElementIdentity that mimics a real-world DOM
 * structure and verifies the ranking output.
 *
 * Architecture: .drytis/EXPANDED_VALIDATION_DESIGN.md §4
 */

import { describe, it, expect } from 'vitest';
import {
  extractCandidatesFromIdentity,
  rankLocatorCandidates,
  isAutoGeneratedId,
  isCssInJsClass,
  LocatorCategory,
} from '../../src/domain/locator-ranking';
import type { ElementIdentity } from '../../src/shared/types';
import { LocatorStrategyType } from '../../src/domain/enums';
import type { RawObservation } from './types';

// ── Helpers ──────────────────────────────────────────────────────────

function makeIdentity(overrides: Partial<ElementIdentity> = {}): ElementIdentity {
  return {
    elementId: 'test-elem-1',
    accessibleName: '',
    ariaRole: null,
    ariaLabel: null,
    ariaLabelledBy: null,
    placeholder: null,
    tag: 'DIV',
    className: null,
    name: null,
    stableId: null,
    testId: null,
    dataCy: null,
    dataQa: null,
    cssSelector: 'body > div',
    xPath: '/html/body/div',
    inIframe: false,
    shadowDom: false,
    ...overrides,
  };
}

function assessLocator(identity: ElementIdentity) {
  const candidates = extractCandidatesFromIdentity(identity);
  const ranked = rankLocatorCandidates(candidates);
  const top = ranked[0] ?? null;
  return { candidates, ranked, top };
}

// ── Raw Observations ─────────────────────────────────────────────────

const observations: RawObservation[] = [];

function recordObs(
  observationId: string,
  scores: RawObservation['scores'],
  observed: string,
  rootCause: string,
  category: RawObservation['category'],
  severity: RawObservation['severity'],
  subsystem: RawObservation['subsystem'],
): void {
  observations.push({
    observationId,
    area: 'locator',
    capabilityId: 'locator-quality',
    framework: null,
    scores,
    support: scores.q3_locator >= 4 ? 'full' : scores.q3_locator >= 2 ? 'partial' : 'unsupported',
    observed,
    rootCause,
    category,
    severity,
    subsystem,
    confidence: 'VERIFIED',
  });
}

// ── Tests ────────────────────────────────────────────────────────────

describe('Locator Quality Assessment', () => {

  describe('LQ-01: Clean testId (baseline)', () => {
    it('testId is #1 ranked locator', () => {
      const id = makeIdentity({
        testId: 'submit-btn',
        ariaRole: 'button',
        accessibleName: 'Submit',
      });
      const { top, ranked } = assessLocator(id);

      expect(top).not.toBeNull();
      expect(top!.type).toBe(LocatorStrategyType.TEST_ID);
      expect(top!.value).toBe('submit-btn');
      expect(top!.confidence).toBeGreaterThanOrEqual(0.90);

      if (top!.type !== LocatorStrategyType.TEST_ID || top!.value !== 'submit-btn') {
        recordObs('LQ-01', { q1_intent: 5, q2_abstraction: 5, q3_locator: 1, q4_description: 5, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
          `Expected testId:submit-btn as #1, got ${top!.type}:${top!.value}`, 'Unexpected ranking', 'implementation-gap', 'P1', 'Locator Ranking');
      } else {
        recordObs('LQ-01', { q1_intent: 5, q2_abstraction: 5, q3_locator: 5, q4_description: 5, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
          'testId correctly ranked #1', 'None', 'implementation-gap', 'P3', 'Locator Ranking');
      }
    });
  });

  describe('LQ-02: Auto-generated React ID filtered', () => {
    it(':r5: ID is filtered, ariaLabel wins', () => {
      const id = makeIdentity({
        stableId: ':r5:',
        ariaLabel: 'Search',
        tag: 'INPUT',
      });
      const { ranked } = assessLocator(id);

      // :r5: should NOT appear in locators
      const reactIdLocator = ranked.find(r => r.value.includes(':r5:'));
      expect(reactIdLocator).toBeUndefined();

      // ariaLabel should be present
      const ariaLocator = ranked.find(r => r.type === LocatorStrategyType.ACCESSIBLE_NAME && r.value === 'Search');
      expect(ariaLocator).toBeDefined();

      const q3 = (!reactIdLocator && ariaLocator) ? 5 : 1;
      recordObs('LQ-02', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        reactIdLocator ? `React ID :r5: leaked into locators at priority ${reactIdLocator.priority}` : 'React auto-generated ID correctly filtered, ariaLabel used instead',
        reactIdLocator ? 'Auto-generated ID filter failed for :r5: pattern' : 'None',
        reactIdLocator ? 'implementation-gap' : 'implementation-gap',
        reactIdLocator ? 'P1' : 'P3',
        'Locator Ranking');
    });
  });

  describe('LQ-03: MUI CSS-in-JS classes filtered', () => {
    it('css-1sq4k6b is filtered from CSS locators', () => {
      // Simulate MUI: className has Mui classes + CSS-in-JS hash
      // The extractor uses cssSelector, not className directly. So the
      // cssSelector would be something like "div.MuiButton-root.css-1sq4k6b"
      const id = makeIdentity({
        cssSelector: 'div.MuiButton-root.css-1sq4k6b',
        ariaRole: 'button',
        accessibleName: 'Save',
        tag: 'DIV',
      });
      const { ranked } = assessLocator(id);

      // CSS-in-JS class should be filtered from CSS locators
      const cssInJsLocator = ranked.find(r => r.type === LocatorStrategyType.CSS && r.value.includes('css-'));
      // accessibleName should rank higher
      const nameLocator = ranked.find(r => r.value === 'Save');

      const q3 = cssInJsLocator ? 2 : (nameLocator ? 5 : 3);
      recordObs('LQ-03', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        cssInJsLocator ? `CSS-in-JS class leaked: ${cssInJsLocator.value}` : 'CSS-in-JS class filtered, accessibleName used',
        cssInJsLocator ? 'isCssInJsClass filter did not catch this pattern' : 'None',
        'implementation-gap', cssInJsLocator ? 'P2' : 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-04: No semantic attributes — structural fallback', () => {
    it('produces CSS or XPath fallback', () => {
      const id = makeIdentity({
        tag: 'DIV',
        cssSelector: 'body > div.cursor-pointer',
        xPath: '/html/body/div[3]',
        stableId: null,
        testId: null,
        ariaLabel: null,
        accessibleName: '',
        ariaRole: null,
      });
      const { top, ranked } = assessLocator(id);

      expect(ranked.length).toBeGreaterThan(0);
      // Should fall back to CSS or XPath
      expect([LocatorStrategyType.CSS, LocatorStrategyType.XPATH]).toContain(top!.type);

      const q3 = top!.type === LocatorStrategyType.CSS ? 3 : 2;
      recordObs('LQ-04', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 2, q5_replay: 3, q6_confidence: 3, q7_evidence: 5, q8_assertion: 5 },
        `Fallback locator: ${top!.type}:${top!.value} (priority ${top!.priority}, confidence ${top!.confidence})`,
        'By design — no semantic anchors available', 'architectural-limitation', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-05: Radix data attributes', () => {
    it('data-radix-* not used as locators, role wins', () => {
      const id = makeIdentity({
        stableId: 'radix-:r2q:',
        ariaRole: 'menuitemcheckbox',
        accessibleName: 'Enable notifications',
        tag: 'DIV',
        cssSelector: 'div[data-radix-collection-item]',
        xPath: '/html/body/div[2]/div[3]',
      });
      const { top, ranked } = assessLocator(id);

      // radix ID should be filtered
      const radixId = ranked.find(r => r.value.includes('radix-') && r.type !== LocatorStrategyType.CSS);
      // role-based locator should win
      const roleLocator = ranked.find(r => r.type === LocatorStrategyType.ROLE);

      const q3 = radixId ? 2 : (roleLocator ? 5 : 3);
      recordObs('LQ-05', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        radixId ? `Radix ID leaked: ${radixId.value}` : (roleLocator ? `Role locator used: ${roleLocator.value}` : `Fallback: ${top!.type}:${top!.value}`),
        radixId ? 'Auto-generated ID filter missed radix- pattern' : 'None',
        'implementation-gap', radixId ? 'P2' : 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-06: Deeply nested with ariaLabelledBy', () => {
    it('ariaLabelledBy produces a locator', () => {
      const id = makeIdentity({
        tag: 'SPAN',
        ariaLabelledBy: 'label-1',
        ariaLabel: null,
        accessibleName: 'Email Address',
        ariaRole: null,
        cssSelector: 'body > form > div > span',
        xPath: '/html/body/form/div/span',
      });
      const { ranked } = assessLocator(id);

      const labelLocator = ranked.find(r => r.value === 'label-1');
      expect(labelLocator).toBeDefined();
      expect(labelLocator!.category || 0).toBeLessThanOrEqual(LocatorCategory.ACCESSIBILITY);

      const q3 = labelLocator ? 4 : 2;
      recordObs('LQ-06', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        labelLocator ? `ariaLabelledBy locator: ${labelLocator.value} at priority ${labelLocator.priority}` : 'ariaLabelledBy not extracted',
        labelLocator ? 'None' : 'extractCandidatesFromIdentity does not handle ariaLabelledBy', 'implementation-gap', labelLocator ? 'P3' : 'P1', 'Locator Ranking');
    });
  });

  describe('LQ-07: Tailwind utility classes', () => {
    it('Tailwind classes produce CSS fallback, accessibleName wins', () => {
      const id = makeIdentity({
        tag: 'BUTTON',
        accessibleName: 'Submit',
        ariaRole: 'button',
        cssSelector: 'body > button.flex.items-center.gap-2.px-4.py-2',
        xPath: '/html/body/button',
      });
      const { top, ranked } = assessLocator(id);

      // accessibleName should rank above CSS
      const nameLocator = ranked.find(r => r.value === 'Submit');
      const roleLocator = ranked.find(r => r.type === LocatorStrategyType.ROLE);
      const cssLocator = ranked.find(r => r.type === LocatorStrategyType.CSS);

      const semanticWinner = nameLocator && (!cssLocator || nameLocator.priority < cssLocator.priority);
      const q3 = semanticWinner ? 5 : 3;
      recordObs('LQ-07', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        semanticWinner ? 'Semantic locator wins over Tailwind CSS' : `CSS fallback used: ${top!.value}`,
        'None', 'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-08: Dynamic aria-label (timestamp)', () => {
    it('Dynamic aria-label is still used (no stability detection)', () => {
      const id = makeIdentity({
        tag: 'BUTTON',
        ariaLabel: 'Close dialog opened 3 seconds ago',
        ariaRole: 'button',
        cssSelector: 'body > button',
        xPath: '/html/body/button',
      });
      const { top } = assessLocator(id);

      // No stability detection — aria-label is always used
      // This is a known limitation: dynamic text in aria-label is unstable for replay
      const q3 = 3;
      recordObs('LQ-08', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 3, q6_confidence: 3, q7_evidence: 5, q8_assertion: 5 },
        `Dynamic aria-label used: "${top!.value}" — no stability detection, fragile for replay`,
        'No dynamic content detection in locator ranking — aria-labels with timestamps or counters are unstable',
        'architectural-limitation', 'P2', 'Locator Ranking');
    });
  });

  describe('LQ-09: Duplicate testId across rows', () => {
    it('Duplicate testId still ranked #1 (no uniqueness detection)', () => {
      const id = makeIdentity({
        testId: 'row',
        ariaRole: 'row',
        accessibleName: 'John Doe',
        tag: 'TR',
      });
      const { top } = assessLocator(id);

      expect(top!.type).toBe(LocatorStrategyType.TEST_ID);
      expect(top!.value).toBe('row');

      // This is a known limitation: testId="row" on every row in a table
      // is not unique, but the locator ranking has no uniqueness awareness
      const q3 = 3;
      recordObs('LQ-09', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 3, q5_replay: 2, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        `Duplicate testId "row" ranked #1 — not unique, but no uniqueness awareness in ranking`,
        'No DOM context awareness in locator ranking — ranking operates on ElementIdentity in isolation, cannot detect duplicate testIds',
        'architectural-limitation', 'P2', 'Locator Ranking');
    });
  });

  describe('LQ-10: SVG icon button', () => {
    it('SVG element without semantic identity uses CSS fallback', () => {
      const id = makeIdentity({
        tag: 'SVG',
        className: 'w-5 h-5',
        cssSelector: 'body > div > button > svg.w-5\\.h-5',
        xPath: '/html/body/div/button/svg',
        accessibleName: '',
        ariaLabel: null,
        ariaRole: null,
        testId: null,
      });
      const { top } = assessLocator(id);

      expect([LocatorStrategyType.CSS, LocatorStrategyType.XPATH]).toContain(top!.type);

      const q3 = 2;
      recordObs('LQ-10', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 2, q5_replay: 2, q6_confidence: 3, q7_evidence: 5, q8_assertion: 5 },
        `SVG icon with no semantic anchors — fallback: ${top!.type}:${top!.value}`,
        'SVG elements often lack aria-label or role — parent button identity not propagated to child SVG',
        'architectural-limitation', 'P2', 'Locator Ranking');
    });
  });

  describe('LQ-11: ContentEditable div (Quill)', () => {
    it('Quill editor uses CSS fallback', () => {
      const id = makeIdentity({
        tag: 'DIV',
        cssSelector: 'div.ql-editor',
        xPath: '/html/body/div[2]/div[1]/div[2]',
        accessibleName: '',
        ariaLabel: null,
        ariaRole: 'textbox',
        // Note: ariaRole textbox with no accessibleName means no role locator
        // from the content category. Only the ariaRole check in accessibility
        // requires ariaLabel too.
        className: 'ql-editor',
      });
      const { top, ranked } = assessLocator(id);

      expect(ranked.length).toBeGreaterThan(0);

      const q3 = top!.type === LocatorStrategyType.CSS ? 3 : 2;
      recordObs('LQ-11', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 3, q5_replay: 3, q6_confidence: 3, q7_evidence: 5, q8_assertion: 5 },
        `Quill editor locator: ${top!.type}:${top!.value} — no semantic anchors for contentEditable`,
        'ContentEditable divs often lack aria-label; the editor framework controls accessibility',
        'architectural-limitation', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-12: Portaled element (Radix dialog)', () => {
    it('Portaled dialog uses accessibleName when available', () => {
      const id = makeIdentity({
        stableId: 'radix-:r2q:',
        ariaRole: 'dialog',
        accessibleName: 'Settings',
        tag: 'DIV',
        cssSelector: 'body > div.radix-popper-content',
        xPath: '/html/body/div[5]',
      });
      const { top, ranked } = assessLocator(id);

      // radix ID should be filtered
      const radixLeaked = ranked.find(r => r.value.includes('radix-:r'));

      // role+accessibleName should produce a content locator
      const roleLocator = ranked.find(r => r.type === LocatorStrategyType.ROLE);

      const q3 = radixLeaked ? 2 : (roleLocator ? 4 : 3);
      recordObs('LQ-12', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 3, q6_confidence: 3, q7_evidence: 5, q8_assertion: 5 },
        radixLeaked ? `Portal ID leaked: ${radixLeaked.value}` : (roleLocator ? `Role locator: ${roleLocator.value}` : `Fallback: ${top!.type}:${top!.value}`),
        radixLeaked ? 'Auto-generated ID filter missed radix-:r pattern' : 'Portaled elements have auto-generated IDs; role+name is the stable anchor',
        radixLeaked ? 'implementation-gap' : 'architectural-limitation',
        radixLeaked ? 'P2' : 'P3', 'Locator Ranking');
    });
  });

  // ── Edge Cases ────────────────────────────────────────────────

  describe('LQ-EC-01: Empty identity', () => {
    it('produces CSS fallback, does not crash', () => {
      const id = makeIdentity({
        tag: 'DIV',
        cssSelector: '',
        xPath: '',
        accessibleName: '',
        stableId: null,
        testId: null,
        ariaLabel: null,
        ariaRole: null,
      });
      const { ranked } = assessLocator(id);

      // Should not crash, should produce 0 locators (all empty filtered)
      expect(ranked).toEqual([]);

      recordObs('LQ-EC-01', { q1_intent: 5, q2_abstraction: 5, q3_locator: 1, q4_description: 1, q5_replay: 1, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
        'Empty identity produces 0 locators — no crash but no locator at all',
        'All fields empty — no candidates to extract', 'architectural-limitation', 'P1', 'Locator Ranking');
    });
  });

  describe('LQ-EC-02: Very long accessibleName', () => {
    it('accessibleName > 100 chars is filtered', () => {
      const longName = 'A'.repeat(200);
      const id = makeIdentity({
        accessibleName: longName,
        ariaRole: 'button',
        tag: 'BUTTON',
        cssSelector: 'body > button',
        xPath: '/html/body/button',
      });
      const { ranked } = assessLocator(id);

      // Long accessibleName should be filtered (>100 chars)
      const longLocator = ranked.find(r => r.value.length > 100);
      expect(longLocator).toBeUndefined();

      // Should still have CSS fallback
      expect(ranked.length).toBeGreaterThan(0);

      const q3 = longLocator ? 2 : 4;
      recordObs('LQ-EC-02', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 3, q5_replay: 4, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        longLocator ? 'Long accessibleName leaked into locators' : 'Long accessibleName correctly filtered, CSS fallback used',
        longLocator ? 'filterValidCandidates 100-char limit not applied' : 'None',
        'implementation-gap', longLocator ? 'P2' : 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-EC-03: Special characters in id', () => {
    it('id with brackets produces CSS with escaped value', () => {
      const id = makeIdentity({
        stableId: 'user[email]',
        tag: 'INPUT',
        ariaRole: 'textbox',
        accessibleName: 'Email',
        cssSelector: 'input#user\\\\\\[email\\\\\\]',
        xPath: '/html/body/form/input[2]',
      });
      const { ranked } = assessLocator(id);

      // Should produce a CSS locator for #user[email]
      // Note: the ranking system doesn't escape CSS — that's the adapter's job
      const cssLocator = ranked.find(r => r.type === LocatorStrategyType.CSS && r.value.includes('user'));

      const q3 = 4;
      recordObs('LQ-EC-03', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 4, q5_replay: 3, q6_confidence: 4, q7_evidence: 5, q8_assertion: 5 },
        cssLocator ? `CSS locator: ${cssLocator.value}` : 'No CSS locator for special-char id',
        'CSS escaping is the adapter\'s responsibility, not the ranking layer', 'implementation-gap', 'P3', 'Locator Ranking');
    });
  });

  describe('LQ-EC-04: Unicode accessibleName', () => {
    it('Unicode characters preserved in locator value', () => {
      const id = makeIdentity({
        accessibleName: '設定',
        ariaRole: 'button',
        tag: 'BUTTON',
        cssSelector: 'body > button',
        xPath: '/html/body/button',
      });
      const { ranked } = assessLocator(id);

      const nameLocator = ranked.find(r => r.value === '設定');
      expect(nameLocator).toBeDefined();

      const q3 = nameLocator ? 5 : 2;
      recordObs('LQ-EC-04', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 5, q5_replay: 5, q6_confidence: 5, q7_evidence: 5, q8_assertion: 5 },
        nameLocator ? 'Unicode accessibleName preserved correctly' : 'Unicode accessibleName lost',
        nameLocator ? 'None' : 'String handling issue', 'implementation-gap', nameLocator ? 'P3' : 'P1', 'Locator Ranking');
    });
  });

  describe('LQ-EC-05: Numeric-only className', () => {
    it('Meaningless className does not crash ranking', () => {
      const id = makeIdentity({
        tag: 'DIV',
        cssSelector: 'div.123.456',
        xPath: '/html/body/div[3]',
        accessibleName: '',
        ariaLabel: null,
        ariaRole: null,
      });
      const { top, ranked } = assessLocator(id);

      expect(ranked.length).toBeGreaterThan(0);
      // Should not crash — meaningless but valid
      const q3 = 2;
      recordObs('LQ-EC-05', { q1_intent: 5, q2_abstraction: 5, q3_locator: q3, q4_description: 1, q5_replay: 2, q6_confidence: 3, q7_evidence: 5, q8_assertion: 5 },
        `Numeric className produces: ${top!.type}:${top!.value} — syntactically valid but meaningless`,
        'No semantic validation of CSS class names — numeric classes are valid CSS but provide no meaning',
        'architectural-limitation', 'P3', 'Locator Ranking');
    });
  });

  // ── Export observations ───────────────────────────────────────

  describe('Observations Summary', () => {
    it('records all locator quality observations', () => {
      // This test exists to ensure the observations array is populated
      // and can be exported by the test runner.
      console.log(`[Locator Quality] ${observations.length} observations recorded`);
      for (const obs of observations) {
        console.log(`  ${obs.observationId}: Q3=${obs.scores.q3_locator} | ${obs.severity} | ${obs.observed}`);
      }
      expect(observations.length).toBeGreaterThanOrEqual(15);
    });
  });
});
