/**
 * Shared Locator Ranking — single source of truth for locator priority,
 * filtering, confidence scoring, and top-N selection.
 *
 * Used by:
 *   - Recording-time: resolveLocatorsForIR() in ir-bridge.ts
 *     (candidates extracted from ElementIdentity)
 *   - Execution-time (Phase 12): live DOM locator discovery
 *     (candidates extracted from Playwright page inspection)
 *
 * Design principle: both paths gather LocatorCandidate[] differently,
 * but both pass through the same ranking rules. This ensures consistent
 * locator quality regardless of source.
 *
 * Ranking hierarchy (highest priority first):
 *   1. Business Identifiers (testId, dataCy, dataQa) — confidence 0.90–0.95
 *   2. Accessibility (ariaLabel, ariaLabelledBy) — confidence 0.80
 *   3. Stable Technical (non-auto-generated id, name) — confidence 0.70–0.75
 *   4. Content-Based (accessibleName, placeholder) — confidence 0.60–0.65
 *   5. Structural (non-CSS-in-Js selectors, XPath) — confidence 0.30–0.40
 */

import { LocatorStrategyType } from './enums';
import type { ElementIdentity } from '../shared/types';

// ── Types ────────────────────────────────────────────────────

/**
 * A raw locator candidate before ranking.
 * Both recording-time and execution-time paths produce these.
 */
export interface LocatorCandidate {
  /** The locator strategy type this candidate maps to. */
  readonly type: LocatorStrategyType;
  /** The raw locator value (attribute value, selector, etc.). */
  readonly value: string;
  /**
   * Category determines base confidence and priority order.
   * Lower number = higher priority.
   */
  readonly category: LocatorCategory;
}

/**
 * Locator categories in priority order.
 * Lower number = higher priority.
 */
export enum LocatorCategory {
  BUSINESS = 1,
  ACCESSIBILITY = 2,
  STABLE_TECHNICAL = 3,
  CONTENT = 4,
  STRUCTURAL = 5,
}

/**
 * A ranked locator — the output of rankLocatorCandidates().
 * Structurally compatible with both LocatorStrategy and ResolvedLocator.
 */
export interface RankedLocator {
  readonly type: LocatorStrategyType;
  readonly value: string;
  readonly priority: number;
  readonly confidence: number;
}

// ── Auto-Generated ID Detection ──────────────────────────────

/**
 * Patterns that identify auto-generated IDs from React, Angular, Vue,
 * MUI, styled-components, etc. These IDs are not stable across builds
 * and should NOT be used as locators.
 */
const AUTO_GENERATED_ID_PATTERNS = [
  /^:r\d+:$/, /^:r\d+_?/, /^react-\d[\d.]*$/, /^mui-\d+$/, /^ng-[\w-]+$/,
  /^cdk-[\w-]+$/, /^v-\d+$/, /^sc-[a-zA-Z0-9]+$/, /^css-[a-zA-Z0-9]+$/,
  /^.__[a-zA-Z0-9]+/, /^rc-\d+$/, /^__BVID__\d+$/, /^headlessui-/, /^radix-/,
  /^__ta-/, /^element-id-\d+$/, /^:S\d+:/, /^[a-f0-9]{16,}$/i,
];

/**
 * Check if an ID value matches a known auto-generated pattern.
 */
export function isAutoGeneratedId(value: string): boolean {
  return AUTO_GENERATED_ID_PATTERNS.some((p) => p.test(value));
}

/**
 * Check if a CSS selector contains CSS-in-JS class names
 * (styled-components, emotion, etc.) that are not stable across builds.
 */
export function isCssInJsClass(selector: string): boolean {
  return /\.(?:css|sc|emotion|styled|react|__)[a-zA-Z0-9_-]{4,}/.test(selector);
}

// ── Category Confidence ──────────────────────────────────────

/**
 * Base confidence scores per category.
 * Individual candidates within a category may have slightly different
 * confidence based on their specific source.
 */
const CATEGORY_CONFIDENCE: Record<LocatorCategory, number> = {
  [LocatorCategory.BUSINESS]: 0.90,
  [LocatorCategory.ACCESSIBILITY]: 0.80,
  [LocatorCategory.STABLE_TECHNICAL]: 0.72,
  [LocatorCategory.CONTENT]: 0.62,
  [LocatorCategory.STRUCTURAL]: 0.35,
};

/**
 * Confidence overrides for specific candidate types within a category.
 * These refine the base category confidence.
 */
const CONFIDENCE_OVERRIDES: Partial<Record<string, number>> = {
  // Business: testId is the gold standard
  'testId:primary': 0.95,
  'testId:secondary': 0.90,
  // Stable technical: non-auto-generated id is better than name
  'stableTechnical:id': 0.75,
  'stableTechnical:name': 0.70,
  // Content: accessibleName is better than placeholder
  'content:accessibleName': 0.65,
  'content:placeholder': 0.60,
  // Structural: CSS is better than XPath
  'structural:css': 0.40,
  'structural:xpath': 0.30,
};

function getConfidence(
  category: LocatorCategory,
  overrideKey?: string,
): number {
  if (overrideKey && CONFIDENCE_OVERRIDES[overrideKey] !== undefined) {
    return CONFIDENCE_OVERRIDES[overrideKey]!;
  }
  return CATEGORY_CONFIDENCE[category];
}

// ── Filtering ────────────────────────────────────────────────

/**
 * Filter out invalid locator candidates:
 *   - Empty values
 *   - Auto-generated IDs (for ID-based locators)
 *   - CSS-in-JS class selectors
 *
 * This is applied before ranking.
 */
export function filterValidCandidates(candidates: readonly LocatorCandidate[]): LocatorCandidate[] {
  return candidates.filter((c) => {
    // Remove empty values
    if (!c.value || !c.value.trim()) return false;

    // For CSS locators that are ID-based, filter auto-generated IDs
    if (c.type === LocatorStrategyType.CSS && c.value.startsWith('#')) {
      const idValue = c.value.slice(1);
      if (isAutoGeneratedId(idValue)) return false;
    }

    // For CSS selectors, filter CSS-in-JS classes
    if (c.type === LocatorStrategyType.CSS && isCssInJsClass(c.value)) {
      return false;
    }

    return true;
  });
}

// ── Ranking ──────────────────────────────────────────────────

/**
 * Rank locator candidates by category priority, assign confidence scores,
 * and return the top N locators.
 *
 * This is the single shared function used by both recording-time and
 * execution-time locator resolution.
 *
 * @param candidates Raw locator candidates from any source.
 * @param maxLocators Maximum number of locators to return (default: 3).
 * @returns Ranked locators sorted by priority (1 = highest).
 */
export function rankLocatorCandidates(
  candidates: readonly LocatorCandidate[],
  maxLocators: number = 3,
): RankedLocator[] {
  // Step 1: Filter invalid candidates
  const valid = filterValidCandidates(candidates);

  // Step 2: Sort by category (lower = higher priority)
  const sorted = [...valid].sort((a, b) => {
    if (a.category !== b.category) {
      return a.category - b.category;
    }
    // Within same category, preserve original order (recording-time priority)
    return 0;
  });

  // Step 3: Deduplicate by (type, value) — keep first occurrence
  const seen = new Set<string>();
  const deduped = sorted.filter((c) => {
    const key = `${c.type}:${c.value}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  // Step 4: Assign priority (1-based) and confidence
  const ranked: RankedLocator[] = deduped.map((c, index) => ({
    type: c.type,
    value: c.value.trim(),
    priority: index + 1,
    confidence: getConfidence(c.category),
  }));

  // Step 5: Cap at maxLocators
  return ranked.slice(0, maxLocators);
}

// ── ElementIdentity → LocatorCandidate[] extractor ───────────

/**
 * Extract locator candidates from an ElementIdentity (recording-time path).
 *
 * This replaces the inline candidate extraction that was previously in
 * resolveLocatorsForIR(). The ranking rules are now in rankLocatorCandidates().
 */
export function extractCandidatesFromIdentity(identity: ElementIdentity): LocatorCandidate[] {
  const candidates: LocatorCandidate[] = [];

  // Category 1: Business Identifiers
  if (identity.testId) {
    candidates.push({
      type: LocatorStrategyType.TEST_ID,
      value: identity.testId,
      category: LocatorCategory.BUSINESS,
    });
  }
  if (identity.dataCy) {
    candidates.push({
      type: LocatorStrategyType.TEST_ID,
      value: identity.dataCy,
      category: LocatorCategory.BUSINESS,
    });
  }
  if (identity.dataQa) {
    candidates.push({
      type: LocatorStrategyType.TEST_ID,
      value: identity.dataQa,
      category: LocatorCategory.BUSINESS,
    });
  }

  // Category 2: Accessibility
  if (identity.ariaLabel) {
    candidates.push({
      type: LocatorStrategyType.ACCESSIBLE_NAME,
      value: identity.ariaLabel,
      category: LocatorCategory.ACCESSIBILITY,
    });
  }
  if (identity.ariaLabelledBy) {
    candidates.push({
      type: LocatorStrategyType.ACCESSIBLE_NAME,
      value: identity.ariaLabelledBy,
      category: LocatorCategory.ACCESSIBILITY,
    });
  }

  // Category 3: Stable Technical
  if (identity.stableId) {
    candidates.push({
      type: LocatorStrategyType.CSS,
      value: `#${identity.stableId}`,
      category: LocatorCategory.STABLE_TECHNICAL,
    });
  }
  if (identity.name) {
    candidates.push({
      type: LocatorStrategyType.LABEL,
      value: identity.name,
      category: LocatorCategory.STABLE_TECHNICAL,
    });
  }

  // Category 4: Content-Based
  if (identity.accessibleName) {
    candidates.push({
      type: LocatorStrategyType.ACCESSIBLE_NAME,
      value: identity.accessibleName,
      category: LocatorCategory.CONTENT,
    });
  }
  if (identity.placeholder) {
    candidates.push({
      type: LocatorStrategyType.LABEL,
      value: identity.placeholder,
      category: LocatorCategory.CONTENT,
    });
  }

  // Category 5: Structural
  if (identity.cssSelector) {
    candidates.push({
      type: LocatorStrategyType.CSS,
      value: identity.cssSelector,
      category: LocatorCategory.STRUCTURAL,
    });
  }
  if (identity.xPath) {
    candidates.push({
      type: LocatorStrategyType.XPATH,
      value: identity.xPath,
      category: LocatorCategory.STRUCTURAL,
    });
  }

  return candidates;
}
