/**
 * Locator Resolution Engine — applies the B4.4 Locator Priority Strategy
 * to element identity and produces resolved locators.
 *
 * Milestone B5.3 (v5.0.0) — Implementation
 *
 * B5.1 §5.2: This is a CAPABILITY (pure function) invoked by the Execution
 * JSON Generator. It is NOT a separate generator — it does not register in
 * the Generator Registry.
 *
 * B5.1 AP5 / B4.4 LP-P1: Deterministic. Same element identity → same
 * resolved locators, every time.
 *
 * B4.4 Frozen Rules Implemented:
 *   - Priority hierarchy: Business → Accessibility → Stable Tech → Content → Structural
 *   - Max 3 locators: primary, secondary, fallback
 *   - Acceptance rules: non-empty, element-specific, syntactically valid
 *   - Disqualifiers: auto-generated IDs, CSS-in-JS class names, ambiguous structural locators
 *   - Navigation exempt from locator rules
 */

import type { ElementIdentity } from '../../shared/types';
import type { ExecutionLocator, LocatorStrategy, LocatorRole } from '../contracts/execution-json-types';

// ── Acceptance Rule Helpers ────────────────────────────────

/**
 * Regex patterns for auto-generated IDs (B4.4 DQ-1).
 *
 * Matches common framework-generated ID patterns:
 *   - React: ":r1:", ":r2:", etc. (React 18 useId)
 *   - Vue: "v-0", "v-1", "input-abc123" (Vue scoped IDs)
 *   - Angular: "ng-0", "ng-trigger-1", "cdk-..." (Angular auto-IDs)
 *   - Emotion/styled-components hash IDs: "sc-abc123", "css-abc123"
 *   - Material-UI: ":r1:", "mui-12345"
 *   - Generic hash-like: long alphanumeric sequences
 */
const AUTO_GENERATED_ID_PATTERNS = [
  /^:r\d+:$/,                   // React 18 useId
  /^:r\d+_?/,                   // React 18 variant
  /^react-\d[\d.]*$/,           // React reconciliation ID (react-3, react-3.7.2.1, etc.)
  /^mui-\d+$/,                  // Material-UI
  /^ng-[\w-]+$/,                // Angular auto-generated
  /^cdk-[\w-]+$/,               // Angular CDK
  /^v-\d+$/,                    // Vue auto-generated
  /^sc-[a-zA-Z0-9]+$/,          // Emotion/styled-components
  /^css-[a-zA-Z0-9]+$/,         // Emotion CSS
  /^.__[a-zA-Z0-9]+/,            // CSS-in-JS generated class
  /^rc-\d+$/,                   // Ant Design / rc-* components
  /^__BVID__\d+$/,              // Bootstrap Vue
  /^headlessui-/,               // Headless UI
  /^radix-/,                    // Radix UI
  /^__ta-/,                     // Test automation generated
  /^element-id-\d+$/,           // Generic generated
  /^:S\d+:/,                    // Solid.js
  /^[a-f0-9]{16,}$/i,           // Generic hash (16+ hex chars)
];

/**
 * Check if an ID value looks auto-generated.
 * B4.4 DQ-1: Auto-generated IDs are rejected.
 */
function isAutoGeneratedId(value: string): boolean {
  return AUTO_GENERATED_ID_PATTERNS.some((pattern) => pattern.test(value));
}

/**
 * Check if a CSS selector contains CSS-in-JS class names.
 * B4.4 DQ-3: CSS-in-JS generated class names are disqualified.
 */
function isCssInJsClass(selector: string): boolean {
  // CSS-in-JS classes often look like: .abc123, .css-abc, .sc-abc, .__abc
  const cssInJsPatterns = /\.(?:css|sc|emotion|styled|react|__)[a-zA-Z0-9_-]{4,}/;
  return cssInJsPatterns.test(selector);
}

/**
 * Check if a locator value is acceptable per B4.4 acceptance rules.
 *
 * AC-1: Non-empty
 * AC-2: Element-specific (not "body", "html", "*", etc.)
 * AC-3: Syntactically valid
 */
function isAcceptable(value: string | null | undefined): value is string {
  if (!value || typeof value !== 'string') return false;
  const trimmed = value.trim();
  if (trimmed.length === 0) return false;
  // Reject overly generic selectors that match the whole page
  const genericValues = ['body', 'html', '*', 'document', 'window', ':root'];
  if (genericValues.includes(trimmed.toLowerCase())) return false;
  // Reject XPath that targets the whole document
  if (/^\/\/html$/i.test(trimmed) || /^\/\/body$/i.test(trimmed) || trimmed === '/*') return false;
  return true;
}

// ── Locator Category Definition ────────────────────────────

/**
 * A locator candidate extracted from element identity.
 * Each candidate knows its strategy and priority order.
 * The priority field is internal — only strategy+value+role are output.
 */
interface LocatorCandidate {
  strategy: LocatorStrategy;
  value: string;
  /** Absolute priority (lower = higher priority). Within-category first, then overall. */
  priority: number;
}

/**
 * Extract a clean ExecutionLocator (strategy+value+role) from a candidate.
 * Strips the internal priority field.
 */
function toLocator(candidate: LocatorCandidate, role: LocatorRole): ExecutionLocator {
  return { strategy: candidate.strategy, value: candidate.value, role };
}

// ── Candidate Extraction ───────────────────────────────────

/**
 * Extract all locator candidates from element identity, in B4.4 priority order.
 *
 * B4.4 §2.1 Priority Hierarchy:
 *   1. Business Identifiers: testId, dataCy, dataQa (sub: data-testid → data-cy → data-qa)
 *   2. Accessibility: ariaLabel, ariaLabelledby
 *   3. Stable Technical: id, name
 *   4. Content-Based: accessibleName(text), placeholder, alt, title
 *   5. Structural: cssSelector, xPath
 *
 * The priority field assigns a monotonically increasing number so the
 * overall order is deterministic.
 */
function extractCandidates(identity: ElementIdentity): LocatorCandidate[] {
  const candidates: LocatorCandidate[] = [];
  let priority = 0;

  // Category 1: Business Identifiers (sub-priority per B4.4 §5.1)
  if (isAcceptable(identity.testId)) {
    candidates.push({ strategy: 'testId', value: identity.testId, priority: priority++ });
  }
  if (isAcceptable(identity.dataCy)) {
    candidates.push({ strategy: 'dataCy', value: identity.dataCy, priority: priority++ });
  }
  if (isAcceptable(identity.dataQa)) {
    candidates.push({ strategy: 'dataQa', value: identity.dataQa, priority: priority++ });
  }

  // Category 2: Accessibility
  if (isAcceptable(identity.ariaLabel)) {
    candidates.push({ strategy: 'ariaLabel', value: identity.ariaLabel, priority: priority++ });
  }
  if (isAcceptable(identity.ariaLabelledBy)) {
    candidates.push({ strategy: 'ariaLabelledby', value: identity.ariaLabelledBy, priority: priority++ });
  }

  // Category 3: Stable Technical
  // id is checked for auto-generation before accepting
  if (isAcceptable(identity.stableId) && !isAutoGeneratedId(identity.stableId)) {
    candidates.push({ strategy: 'id', value: identity.stableId, priority: priority++ });
  }
  if (isAcceptable(identity.name)) {
    candidates.push({ strategy: 'name', value: identity.name, priority: priority++ });
  }

  // Category 4: Content-Based
  // accessibleName is the computed accessible name — maps to "text" strategy
  if (isAcceptable(identity.accessibleName)) {
    candidates.push({ strategy: 'text', value: identity.accessibleName, priority: priority++ });
  }
  if (isAcceptable(identity.placeholder)) {
    candidates.push({ strategy: 'placeholder', value: identity.placeholder, priority: priority++ });
  }
  // alt and title are not captured in current ElementIdentity but are listed
  // in B4.4 §5.1 for future. They are handled here when the fields exist.

  // Category 5: Structural (last resort)
  // CSS-in-JS class names are disqualified (B4.4 DQ-3)
  if (isAcceptable(identity.cssSelector) && !isCssInJsClass(identity.cssSelector)) {
    candidates.push({ strategy: 'css', value: identity.cssSelector, priority: priority++ });
  }
  if (isAcceptable(identity.xPath)) {
    candidates.push({ strategy: 'xpath', value: identity.xPath, priority: priority++ });
  }

  return candidates;
}

// ── Category Tracking (for secondary from different category) ──

/**
 * Get the B4.4 category number for a strategy.
 * Used to ensure secondary/fallback locators prefer different categories.
 */
function getCategoryForStrategy(strategy: LocatorStrategy): number {
  switch (strategy) {
    case 'testId':
    case 'dataCy':
    case 'dataQa':
    case 'dataTest':
    case 'dataAutomationId':
      return 1; // Business
    case 'ariaLabel':
    case 'ariaLabelledby':
      return 2; // Accessibility
    case 'id':
    case 'name':
      return 3; // Stable Technical
    case 'text':
    case 'placeholder':
    case 'alt':
    case 'title':
      return 4; // Content-Based
    case 'css':
    case 'xpath':
      return 5; // Structural
    default:
      return 99;
  }
}

// ── Result Type ────────────────────────────────────────────

/**
 * Result of locator resolution.
 */
export interface LocatorResolutionResult {
  /** Resolved locators (0–3 entries). Empty if resolution failed. */
  locators: ExecutionLocator[];
  /** Warnings detected during resolution. */
  warnings: string[];
}

// ── Public API ─────────────────────────────────────────────

/**
 * Resolve locators for an element identity.
 *
 * B5.1 §5.2: Pure function — element identity in, resolved locators out.
 * B4.4 §3.6: Maximum 3 locators (primary + secondary + fallback).
 * B4.4 §3.1: Exactly one primary when locators exist.
 * B4.4 §2.1.1: Hierarchy operates on available valid candidates —
 * first valid category becomes primary, cascades top-down.
 *
 * @param identity  The element identity from a Canonical Test Step.
 * @returns         Resolved locators (0–3) and any warnings.
 */
export function resolveLocators(identity: ElementIdentity): LocatorResolutionResult {
  const warnings: string[] = [];

  // 1. Extract candidates in priority order
  const candidates = extractCandidates(identity);

  // 2. If no candidates, resolution failed
  if (candidates.length === 0) {
    return {
      locators: [],
      warnings: ['No accepted locators found — element identity has no valid identifiers'],
    };
  }

  // 3. Assign roles: primary is first (highest priority).
  //    Secondary prefers different category. Fallback is next available.
  const locators: ExecutionLocator[] = [];

  // Primary — always the highest priority candidate
  const primary = candidates[0];
  locators.push(toLocator(primary, 'primary'));

  // Check for auto-generated ID warning
  if (primary.strategy === 'id' && identity.stableId && isAutoGeneratedId(identity.stableId)) {
    // This shouldn't happen since we filter them, but if somehow we got here
    warnings.push('Primary locator is an auto-generated ID — this may be unstable');
  }

  // Warning if primary is structural (low confidence)
  const primaryCategory = getCategoryForStrategy(primary.strategy);
  if (primaryCategory === 5) {
    warnings.push('Primary locator is a structural selector — low confidence for stability');
  }

  // Secondary — prefer a different category from primary
  const primaryCat = getCategoryForStrategy(primary.strategy);
  let secondary: LocatorCandidate | undefined = candidates.find(
    (c, idx) => idx > 0 && getCategoryForStrategy(c.strategy) !== primaryCat,
  );

  // If no different-category candidate, take the next available
  if (!secondary && candidates.length > 1) {
    secondary = candidates[1];
  }

  if (secondary) {
    locators.push(toLocator(secondary, 'secondary'));
  }

  // Fallback — next available candidate not already used
  const usedStrategies = new Set(locators.map((l) => l.strategy));
  const fallback = candidates.find(
    (c) => !usedStrategies.has(c.strategy),
  );

  if (fallback) {
    locators.push(toLocator(fallback, 'fallback'));
  }

  // Enforce max 3 (B4.4 §3.6)
  const finalLocators = locators.slice(0, 3);

  return { locators: finalLocators, warnings };
}
