/**
 * IR Bridge — the single integration point where recording outputs converge
 * into a unified ExecutionIRPlan.
 *
 * Phase 8 — Milestone 8.2
 *
 * Architecture (see docs/handover/14-target-generation-architecture.md):
 *   SessionEvent[] + DetectedInteraction[] + ApplicationKnowledgeFragment
 *     → IR Bridge → ExecutionIRPlan
 *
 * The bridge is a pure function: same inputs → same plan, every time.
 * No side effects, no storage reads/writes. The caller (service worker)
 * handles persistence.
 *
 * Each input provides unique, non-overlapping data:
 *   SessionEvent[] — locators, input values, DOM context, AI enrichment
 *   DetectedInteraction[] — type classification (40 types), metadata, confidence
 *   KnowledgeFragment — assertions, business field labels, workflow structure
 */

import {
  IRAction,
  DEFAULT_EXECUTION_PARAMETERS,
  type IRStep,
  type ExecutionIRPlan,
  type ResolvedLocator,
  type ResolvedTarget,
  type ElementTarget,
  type IRAssertion,
  type IREnvironment,
  type IRInput,
} from '../domain/execution-ir/types';
import {
  LocatorStrategyType,
  ValidationType,
  ValidationComparison,
  ValidationSeverity,
} from '../domain/enums';
import type { SessionEvent, ElementIdentity, AIUnderstanding } from '../shared/types';
import type { DetectedInteraction, InteractionType } from '../classifier/interaction-types';
import type {
  ApplicationKnowledgeFragment,
  InteractionContract,
  LogicalAction,
} from '../domain/entities/application-knowledge';
import type { IRBridgeInput } from './ir-bridge-input';

// ── Interaction Type → IRAction Mapping ────────────────────

const INTERACTION_TO_IR_ACTION: Record<InteractionType, IRAction> = {
  // Navigation
  PageNavigation: IRAction.NAVIGATE,
  Back: IRAction.NAVIGATE,
  Forward: IRAction.NAVIGATE,
  Refresh: IRAction.NAVIGATE,
  // Mouse
  Click: IRAction.CLICK,
  DoubleClick: IRAction.CLICK,
  RightClick: IRAction.CLICK,
  Hover: IRAction.HOVER,
  DragDrop: IRAction.CLICK,
  // Text Entry
  TextEntry: IRAction.FILL,
  // Selection Controls
  NativeDropdown: IRAction.SELECT,
  CustomDropdown: IRAction.SELECT,
  Autocomplete: IRAction.SELECT,
  MultiSelect: IRAction.SELECT,
  Checkbox: IRAction.TOGGLE,
  RadioButton: IRAction.SELECT,
  ToggleSwitch: IRAction.TOGGLE,
  Slider: IRAction.FILL,
  // Date & Time
  DatePicker: IRAction.SELECT_DATE,
  TimePicker: IRAction.SELECT_DATE,
  DateTimePicker: IRAction.SELECT_DATE,
  // File Upload
  FileUpload: IRAction.FILL,
  DragDropUpload: IRAction.FILL,
  // Navigation UI
  Link: IRAction.CLICK,
  Tab: IRAction.CLICK,
  Menu: IRAction.CLICK,
  Breadcrumb: IRAction.CLICK,
  // Scrolling — noise, filtered out
  PageScroll: IRAction.CLICK,
  ContainerScroll: IRAction.CLICK,
  InfiniteScroll: IRAction.CLICK,
  // Dialogs
  BrowserAlert: IRAction.CLICK,
  Modal: IRAction.CLICK,
  Drawer: IRAction.CLICK,
  Popover: IRAction.CLICK,
  Tooltip: IRAction.HOVER,
  // Window & Frame
  NewTab: IRAction.CLICK,
  NewWindow: IRAction.CLICK,
  Iframe: IRAction.CLICK,
  // Unknown
  Unknown: IRAction.CLICK,
};

// ── Locator Resolution (ElementIdentity → ResolvedLocator[]) ──

/**
 * Resolve locators from ElementIdentity using the B4.4 priority strategy.
 *
 * Priority hierarchy: Business → Accessibility → Stable Tech → Content → Structural.
 * Max 3 locators. Maps the existing locator-resolution-engine logic to IR types.
 *
 * This produces ResolvedLocator[] (IR type) instead of ExecutionLocator[] (legacy type).
 */
function resolveLocatorsForIR(identity: ElementIdentity): ResolvedLocator[] {
  const locators: ResolvedLocator[] = [];
  let priority = 1;

  // Category 1: Business Identifiers
  if (identity.testId) {
    locators.push({ type: LocatorStrategyType.TEST_ID, value: identity.testId, priority: priority++, confidence: 0.95 });
  }
  if (identity.dataCy) {
    locators.push({ type: LocatorStrategyType.TEST_ID, value: identity.dataCy, priority: priority++, confidence: 0.9 });
  }
  if (identity.dataQa) {
    locators.push({ type: LocatorStrategyType.TEST_ID, value: identity.dataQa, priority: priority++, confidence: 0.9 });
  }

  // Category 2: Accessibility
  if (identity.ariaLabel) {
    locators.push({ type: LocatorStrategyType.ACCESSIBLE_NAME, value: identity.ariaLabel, priority: priority++, confidence: 0.8 });
  }
  if (identity.ariaLabelledBy) {
    locators.push({ type: LocatorStrategyType.ACCESSIBLE_NAME, value: identity.ariaLabelledBy, priority: priority++, confidence: 0.8 });
  }

  // Category 3: Stable Technical
  if (identity.stableId && !isAutoGeneratedId(identity.stableId)) {
    locators.push({ type: LocatorStrategyType.CSS, value: `#${identity.stableId}`, priority: priority++, confidence: 0.75 });
  }
  if (identity.name) {
    locators.push({ type: LocatorStrategyType.LABEL, value: identity.name, priority: priority++, confidence: 0.7 });
  }

  // Category 4: Content-Based
  if (identity.accessibleName) {
    locators.push({ type: LocatorStrategyType.ACCESSIBLE_NAME, value: identity.accessibleName, priority: priority++, confidence: 0.65 });
  }
  if (identity.placeholder) {
    locators.push({ type: LocatorStrategyType.LABEL, value: identity.placeholder, priority: priority++, confidence: 0.6 });
  }

  // Category 5: Structural
  if (identity.cssSelector && !isCssInJsClass(identity.cssSelector)) {
    locators.push({ type: LocatorStrategyType.CSS, value: identity.cssSelector, priority: priority++, confidence: 0.4 });
  }
  if (identity.xPath) {
    locators.push({ type: LocatorStrategyType.XPATH, value: identity.xPath, priority: priority++, confidence: 0.3 });
  }

  return locators.slice(0, 3);
}

// ── Auto-Generated ID Detection (from locator-resolution-engine) ──

const AUTO_GENERATED_ID_PATTERNS = [
  /^:r\d+:$/, /^:r\d+_?/, /^react-\d[\d.]*$/, /^mui-\d+$/, /^ng-[\w-]+$/,
  /^cdk-[\w-]+$/, /^v-\d+$/, /^sc-[a-zA-Z0-9]+$/, /^css-[a-zA-Z0-9]+$/,
  /^.__[a-zA-Z0-9]+/, /^rc-\d+$/, /^__BVID__\d+$/, /^headlessui-/, /^radix-/,
  /^__ta-/, /^element-id-\d+$/, /^:S\d+:/, /^[a-f0-9]{16,}$/i,
];

function isAutoGeneratedId(value: string): boolean {
  return AUTO_GENERATED_ID_PATTERNS.some((p) => p.test(value));
}

function isCssInJsClass(selector: string): boolean {
  return /\.(?:css|sc|emotion|styled|react|__)[a-zA-Z0-9_-]{4,}/.test(selector);
}

// ── Target Resolution (ElementIdentity → ResolvedTarget) ───

function resolveElementTarget(identity: ElementIdentity): ElementTarget {
  const locators = resolveLocatorsForIR(identity);
  return {
    kind: 'element',
    elementId: identity.elementId,
    elementName: identity.accessibleName || identity.ariaLabel || identity.tag,
    pageOrComponent: 'main',
    resolvedLocators: locators,
  };
}

function resolveUrlTarget(url: string): ResolvedTarget {
  return { kind: 'url', url };
}

// ── Description Generation ─────────────────────────────────

function generateDescription(
  interaction: DetectedInteraction,
  event: SessionEvent | undefined,
  logicalAction: LogicalAction | undefined,
): string {
  const name = getElementDisplayName(interaction, event);
  const businessField = logicalAction?.businessField;

  switch (interaction.type) {
    case 'TextEntry': {
      const value = event?.type === 'text' ? event.value : interaction.metadata.textValue ?? '';
      return businessField
        ? `Fill "${value}" in the ${businessField} field`
        : `Fill "${value}" in the ${name}`;
    }
    case 'Checkbox':
    case 'ToggleSwitch': {
      const checked = event?.type === 'checkbox' ? event.checked : interaction.metadata.checked ?? false;
      return businessField
        ? `${checked ? 'Check' : 'Uncheck'} the ${businessField}`
        : `${checked ? 'Check' : 'Uncheck'} the ${name}`;
    }
    case 'NativeDropdown':
    case 'CustomDropdown':
    case 'Autocomplete':
    case 'MultiSelect':
    case 'RadioButton': {
      const value = event?.type === 'select' ? event.value : interaction.metadata.selectedValue ?? '';
      return businessField
        ? `Select "${value}" from the ${businessField}`
        : `Select "${value}" from the ${name}`;
    }
    case 'DatePicker':
    case 'TimePicker':
    case 'DateTimePicker': {
      const value = event?.type === 'dateSelect' ? event.displayValue : interaction.metadata.dateValue ?? '';
      return businessField
        ? `Select ${value} in the ${businessField}`
        : `Select ${value} in the ${name}`;
    }
    case 'PageNavigation':
    case 'Back':
    case 'Forward':
    case 'Refresh': {
      const url = event?.type === 'navigation' ? event.url : interaction.metadata.url ?? '';
      return `Navigate to ${url}`;
    }
    case 'Hover':
      return `Hover over the ${name}`;
    case 'Slider': {
      const value = interaction.metadata.sliderValue ?? '';
      return businessField
        ? `Set the ${businessField} to ${value}`
        : `Set the slider to ${value}`;
    }
    case 'FileUpload':
    case 'DragDropUpload': {
      const count = interaction.metadata.fileCount ?? 1;
      return businessField
        ? `Upload ${count} file(s) to the ${businessField}`
        : `Upload ${count} file(s)`;
    }
    case 'PageScroll':
    case 'ContainerScroll':
    case 'InfiniteScroll':
      return `Scroll the page`;
    case 'Tab': {
      const tab = interaction.metadata.selectedTab ?? name;
      return `Click the "${tab}" tab`;
    }
    case 'Link':
      return `Click the "${name}" link`;
    case 'Modal':
    case 'Drawer':
    case 'Popover':
      return `Interact with the ${interaction.metadata.surfaceLabel ?? name}`;
    case 'BrowserAlert': {
      const result = interaction.metadata.dialogResult ?? '';
      return `${result} the ${interaction.metadata.dialogType ?? 'dialog'}`;
    }
    default:
      return businessField
        ? `Click the ${businessField}`
        : `Click the ${name}`;
  }
}

function generatePlainEnglish(
  interaction: DetectedInteraction,
  event: SessionEvent | undefined,
  logicalAction: LogicalAction | undefined,
): string {
  // plainEnglish is a simpler, more human-friendly version
  const description = generateDescription(interaction, event, logicalAction);
  // Capitalize first letter
  return description.charAt(0).toUpperCase() + description.slice(1);
}

function getElementDisplayName(
  interaction: DetectedInteraction,
  event: SessionEvent | undefined,
): string {
  if (interaction.target?.accessibleName) {
    return interaction.target.accessibleName;
  }
  if (interaction.target?.ariaLabel) {
    return interaction.target.ariaLabel;
  }
  if (event && 'elementIdentity' in event) {
    return event.elementIdentity.accessibleName || event.elementIdentity.ariaLabel || event.elementIdentity.tag;
  }
  return interaction.metadata.accessibleName ?? 'element';
}

// ── Input Value Extraction ─────────────────────────────────

function extractInputValue(
  interaction: DetectedInteraction,
  event: SessionEvent | undefined,
): IRInput {
  switch (interaction.type) {
    case 'TextEntry':
      return event?.type === 'text' ? event.value : (interaction.metadata.textValue ?? null);

    case 'Checkbox':
    case 'ToggleSwitch':
      return event?.type === 'checkbox' ? event.checked : (interaction.metadata.checked ?? null);

    case 'NativeDropdown':
    case 'CustomDropdown':
    case 'Autocomplete':
    case 'MultiSelect':
    case 'RadioButton':
      return event?.type === 'select' ? event.value : (interaction.metadata.selectedValue ?? null);

    case 'DatePicker':
    case 'TimePicker':
    case 'DateTimePicker':
      return event?.type === 'dateSelect' ? event.isoValue : (interaction.metadata.dateValue ?? null);

    case 'Slider':
      return interaction.metadata.sliderValue ?? null;

    case 'PageNavigation':
    case 'Back':
    case 'Forward':
    case 'Refresh':
      return event?.type === 'navigation' ? event.url : (interaction.metadata.url ?? null);

    default:
      return null;
  }
}

// ── AI Enrichment Extraction ───────────────────────────────

function extractAIEnrichment(event: SessionEvent | undefined): AIUnderstanding | null {
  if (!event) return null;
  if (!('aiUnderstanding' in event)) return null;
  return event.aiUnderstanding ?? null;
}

// ── Assertion Derivation (from Knowledge Fragment) ─────────

/**
 * Derive IRAssertion[] from InteractionContract.constraints.
 *
 * Maps DOM constraints captured by the enrichment pipeline into
 * executable validation assertions.
 */
function deriveAssertions(
  elementId: string,
  fragment: ApplicationKnowledgeFragment | null,
): IRAssertion[] {
  if (!fragment) return [];

  // Find the interaction contract that applies to this element
  const contract = fragment.interactionContracts.find(
    (c) => c.appliesTo.type === 'element' && c.appliesTo.id === elementId,
  );

  if (!contract) return [];

  return constraintsToAssertions(contract, elementId);
}

function constraintsToAssertions(
  contract: InteractionContract,
  elementId: string,
): IRAssertion[] {
  const assertions: IRAssertion[] = [];
  const c = contract.constraints;
  const target: ResolvedTarget = {
    kind: 'element',
    elementId,
    elementName: '',
    pageOrComponent: '',
    resolvedLocators: [],
  };

  // required → presence assertion
  if (c.required === true) {
    assertions.push({
      type: ValidationType.PRESENCE,
      comparison: ValidationComparison.IS_TRUE,
      expectedValue: true,
      severity: ValidationSeverity.HARD,
      target,
      property: 'required',
    });
  }

  // valueRange (min/max) → comparison assertions
  if (c.valueRange) {
    if (c.valueRange.min !== null && c.valueRange.min !== undefined) {
      assertions.push({
        type: ValidationType.ATTRIBUTE_MATCH,
        comparison: ValidationComparison.GREATER_THAN,
        expectedValue: c.valueRange.min,
        severity: ValidationSeverity.SOFT,
        target,
        property: 'min',
      });
    }
    if (c.valueRange.max !== null && c.valueRange.max !== undefined) {
      assertions.push({
        type: ValidationType.ATTRIBUTE_MATCH,
        comparison: ValidationComparison.LESS_THAN,
        expectedValue: c.valueRange.max,
        severity: ValidationSeverity.SOFT,
        target,
        property: 'max',
      });
    }
  }

  // lengthRange (minLength/maxLength)
  if (c.lengthRange) {
    if (c.lengthRange.minLength !== null && c.lengthRange.minLength !== undefined) {
      assertions.push({
        type: ValidationType.ATTRIBUTE_MATCH,
        comparison: ValidationComparison.GREATER_THAN,
        expectedValue: c.lengthRange.minLength,
        severity: ValidationSeverity.SOFT,
        target,
        property: 'minlength',
      });
    }
    if (c.lengthRange.maxLength !== null && c.lengthRange.maxLength !== undefined) {
      assertions.push({
        type: ValidationType.ATTRIBUTE_MATCH,
        comparison: ValidationComparison.LESS_THAN,
        expectedValue: c.lengthRange.maxLength,
        severity: ValidationSeverity.SOFT,
        target,
        property: 'maxlength',
      });
    }
  }

  // format (regex pattern)
  if (c.format?.regex) {
    assertions.push({
      type: ValidationType.TEXT_MATCH,
      comparison: ValidationComparison.MATCHES,
      expectedValue: c.format.regex,
      severity: ValidationSeverity.SOFT,
      target,
      property: 'pattern',
    });
  }

  // validOptions → equality assertion (value must be one of)
  if (c.validOptions && c.validOptions.length > 0) {
    assertions.push({
      type: ValidationType.EQUALITY,
      comparison: ValidationComparison.EQUALS,
      expectedValue: c.validOptions,
      severity: ValidationSeverity.SOFT,
      target,
      property: 'value',
    });
  }

  return assertions;
}

// ── Event ↔ Interaction Correlation ────────────────────────

/**
 * Build a lookup from actionId → SessionEvent for fast correlation.
 */
function buildEventIndex(events: SessionEvent[]): Map<string, SessionEvent> {
  const index = new Map<string, SessionEvent>();
  for (const event of events) {
    index.set(event.actionId, event);
  }
  return index;
}

/**
 * Find the SessionEvent that corresponds to a DetectedInteraction.
 * DetectedInteraction.eventIds links back to the raw events.
 */
function findCorrespondingEvent(
  interaction: DetectedInteraction,
  eventIndex: Map<string, SessionEvent>,
): SessionEvent | undefined {
  for (const eventId of interaction.eventIds) {
    const event = eventIndex.get(eventId);
    if (event) return event;
  }
  return undefined;
}

/**
 * Find the LogicalAction that corresponds to a transition/interaction.
 * Uses timestamp proximity — the LogicalAction whose timestamp is closest.
 */
function findLogicalAction(
  interaction: DetectedInteraction,
  fragment: ApplicationKnowledgeFragment | null,
): LogicalAction | undefined {
  if (!fragment) return undefined;

  // Try to match by transition IDs in the logical action
  // LogicalAction.transitionIds contains transition IDs from the enrichment pipeline
  // These correspond to ObservedTransition.transitionId, which were mapped from
  // DetectedInteraction.interactionId in the domain adapter.
  const match = fragment.logicalActions.find(
    (la) => la.transitionIds.includes(interaction.interactionId),
  );
  if (match) return match;

  // Fallback: no match found
  return undefined;
}

// ── Noise Filtering ────────────────────────────────────────

/**
 * Interaction types that produce no meaningful test step.
 * Filtered out during IR plan construction.
 */
const NOISE_TYPES: Set<InteractionType> = new Set([
  'PageScroll',
  'ContainerScroll',
  'InfiniteScroll',
  'Unknown',
]);

// ── Readability Rules ──────────────────────────────────────

/**
 * Apply readability rules to IRStep[].
 *
 * OR-1: Merge consecutive focus+click on the same element into a single CLICK step.
 * (In the recording pipeline, focus and click are often captured as separate events,
 * but they represent a single user action.)
 *
 * Note: In the current pipeline, DetectedInteractions are already classified at the
 * interaction level (not the raw event level), so duplicate focus+click patterns
 * are rare. This rule handles the edge case where they slip through.
 */
function applyReadabilityRules(steps: IRStep[]): IRStep[] {
  if (steps.length <= 1) return steps;

  const result: IRStep[] = [];
  let i = 0;

  while (i < steps.length) {
    const current = steps[i];
    const next = steps[i + 1];

    // OR-1: Merge consecutive CLICK on same element
    if (
      next &&
      current.action === IRAction.CLICK &&
      next.action === IRAction.CLICK &&
      current.target.kind === 'element' &&
      next.target.kind === 'element' &&
      current.target.elementId === next.target.elementId
    ) {
      // Skip the duplicate — keep only the first
      result.push(current);
      i += 2;
    } else {
      result.push(current);
      i++;
    }
  }

  // Re-number order after merging
  return result.map((step, idx) => ({ ...step, order: idx }));
}

// ── Main Build Function ────────────────────────────────────

/**
 * Build an ExecutionIRPlan from recording outputs.
 *
 * This is the single integration point where:
 *   - SessionEvent[] provides locators, input values, DOM context, AI enrichment
 *   - DetectedInteraction[] provides classification (40 types), metadata, confidence
 *   - ApplicationKnowledgeFragment provides assertions, business fields, workflow structure
 *
 * The plan produced is the single source of truth for all downstream phases
 * (code generation, test execution, staleness detection).
 *
 * @param input Encapsulated bridge inputs (see IRBridgeInput)
 * @returns ExecutionIRPlan — the unified execution representation
 */
export function build(input: IRBridgeInput): ExecutionIRPlan {
  const { events, interactions, fragment, recordingContext, testCaseName } = input;

  const eventIndex = buildEventIndex(events);
  const steps: IRStep[] = [];
  let stepCounter = 0;

  for (const interaction of interactions) {
    // Filter noise interactions
    if (NOISE_TYPES.has(interaction.type)) continue;

    const event = findCorrespondingEvent(interaction, eventIndex);
    const logicalAction = findLogicalAction(interaction, fragment);

    // Determine action
    const action = INTERACTION_TO_IR_ACTION[interaction.type] ?? IRAction.CLICK;

    // Resolve target
    let target: ResolvedTarget;
    if (action === IRAction.NAVIGATE) {
      const url = event?.type === 'navigation' ? event.url : (interaction.metadata.url ?? recordingContext.startUrl);
      target = resolveUrlTarget(url);
    } else if (interaction.target) {
      target = resolveElementTarget(interaction.target);
    } else if (event && 'elementIdentity' in event) {
      target = resolveElementTarget(event.elementIdentity);
    } else {
      target = { kind: 'none' };
    }

    // Extract input value
    const inputValue = extractInputValue(interaction, event);

    // Generate description
    const description = generateDescription(interaction, event, logicalAction);
    const plainEnglish = generatePlainEnglish(interaction, event, logicalAction);

    // Extract AI enrichment
    const aiEnrichment = extractAIEnrichment(event);

    // Source event ID
    const sourceEventId = interaction.eventIds[0] ?? event?.actionId;

    // Derive assertions from knowledge fragment
    const elementId = target.kind === 'element' ? target.elementId : '';
    const assertions = deriveAssertions(elementId, fragment);

    // Execution parameters — default, with wait strategy based on confidence
    const executionParameters = {
      ...DEFAULT_EXECUTION_PARAMETERS,
      waitStrategy: interaction.confidence < 0.7 ? ('visible' as const) : DEFAULT_EXECUTION_PARAMETERS.waitStrategy,
    };

    steps.push({
      id: `step-${String(stepCounter + 1).padStart(4, '0')}`,
      order: stepCounter,
      action,
      description,
      target,
      input: inputValue,
      assertions,
      executionParameters,
      aiEnrichment,
      sourceEventId,
      plainEnglish,
    });

    stepCounter++;
  }

  // Apply readability rules (merge duplicates, re-number)
  const finalSteps = applyReadabilityRules(steps);

  // Derive tags from workflow surfaces
  const tags = deriveTags(fragment, recordingContext);

  // Build environment
  const environment: IREnvironment = {
    baseUrl: recordingContext.startUrl,
    browser: 'chrome',
    viewport: { width: 1280, height: 720 },
  };

  return {
    testCaseId: `tc-${Date.now()}`,
    testCaseVersionId: `tcv-${Date.now()}`,
    testCaseVersionNumber: 1,
    title: testCaseName,
    tags,
    environment,
    steps: finalSteps,
  };
}

/**
 * Derive tags from the knowledge fragment's recorded workflow.
 * Uses surface transition URLs as tags (e.g., "login", "dashboard").
 */
function deriveTags(
  fragment: ApplicationKnowledgeFragment | null,
  recordingContext: IRBridgeInput['recordingContext'],
): string[] {
  const tags: string[] = [];

  // Add the start URL path segment as a tag
  try {
    const url = new URL(recordingContext.startUrl);
    const pathSegment = url.pathname.split('/').filter(Boolean)[0];
    if (pathSegment) tags.push(pathSegment);
  } catch {
    // Ignore invalid URLs
  }

  // Add surface transitions from the fragment
  if (fragment?.recordedWorkflow.surfaceTransitions) {
    for (const transition of fragment.recordedWorkflow.surfaceTransitions) {
      try {
        const url = new URL(transition.toUrl);
        const segment = url.pathname.split('/').filter(Boolean)[0];
        if (segment && !tags.includes(segment)) {
          tags.push(segment);
        }
      } catch {
        // Ignore invalid URLs
      }
    }
  }

  return tags.slice(0, 5); // Max 5 tags
}
