/**
 * Playwright Project Generator — Milestone 4 + Milestone 5
 *
 * Produces a complete, production-quality Playwright project from an
 * ExecutionIRPlan. Implements the IRCodeGenerator interface from the
 * execution-ir design (§4.2).
 *
 * Generated project structure (flat pattern — M4):
 *   package.json
 *   playwright.config.ts
 *   tsconfig.json
 *   .gitignore
 *   tests/<slug>.spec.ts
 *
 * Generated project structure (page-object pattern — M5):
 *   package.json
 *   playwright.config.ts
 *   tsconfig.json
 *   .gitignore
 *   tests/<slug>.spec.ts       (uses page objects)
 *   pages/<page-slug>.ts       (one per pageOrComponent)
 *
 * Reference: execution-ir-design.md §4.2, §7
 *            playwright.dev/docs/best-practices
 */

import type { ExecutionIRPlan, IREnvironment } from '../../domain/execution-ir/types';
import type {
  IRCodeGenerator,
  GeneratorConfig,
  GenerationResult,
  GeneratedFile,
} from '../../domain/execution-ir/adapters/ir-code-generator';
import { renderTestFile } from './test-function-renderer';
import { renderPomTestFile } from './test-function-renderer';
import { renderPageObjectFiles } from './page-object-renderer';

// ── Constants ─────────────────────────────────────────────

const PLAYWRIGHT_VERSION = '^1.52.0';

// ── Main Class ────────────────────────────────────────────

/**
 * Playwright code generator implementing the IRCodeGenerator interface.
 *
 * Pure: given the same plan + config, always produces the same output.
 * No I/O, no file system access — returns in-memory GeneratedFile[].
 */
export class PlaywrightCodeGenerator implements IRCodeGenerator {
  /**
   * Generate a complete Playwright project from an IR plan.
   */
  async generate(
    plan: ExecutionIRPlan,
    config: GeneratorConfig,
  ): Promise<GenerationResult> {
    const files = buildProjectFiles(plan, config);

    return {
      files,
      projectMetadata: {
        engine: 'playwright',
        language: config.language,
        pattern: config.pattern,
        fileCount: files.length,
      },
    };
  }
}

// Convenience function for synchronous access (no I/O involved).
export function buildProjectFiles(
  plan: ExecutionIRPlan,
  config?: GeneratorConfig,
): GeneratedFile[] {
  const baseFiles = [
    buildPackageJson(plan),
    buildPlaywrightConfig(plan),
    config?.pattern === 'page-object' ? buildTsConfig(true) : buildTsConfig(),
    buildGitIgnore(),
  ];

  if (config?.pattern === 'page-object') {
    // POM mode: test file uses page objects + page object files
    const testFile = buildPomTestSpec(plan);
    const pageObjectFiles = renderPageObjectFiles(plan);
    return [...baseFiles, testFile, ...pageObjectFiles];
  }

  // Flat mode (default)
  return [...baseFiles, buildTestSpec(plan)];
}

// ── File Builders ─────────────────────────────────────────

/**
 * Generate package.json.
 *
 * Design decisions:
 * - private: true — test projects are never published
 * - Only devDependencies — no runtime deps needed
 * - Standard Playwright scripts (test, test:headed, test:ui, report)
 */
export function buildPackageJson(plan: ExecutionIRPlan): GeneratedFile {
  const name = slugify(plan.title);
  const content = JSON.stringify({
    name,
    version: '1.0.0',
    private: true,
    description: `Playwright tests for ${plan.title}`,
    scripts: {
      test: 'npx playwright test',
      'test:headed': 'npx playwright test --headed',
      'test:ui': 'npx playwright test --ui',
      report: 'npx playwright show-report',
    },
    devDependencies: {
      '@playwright/test': PLAYWRIGHT_VERSION,
    },
  }, null, 2);

  return { path: 'package.json', content: content + '\n' };
}

/**
 * Generate playwright.config.ts following official best practices.
 *
 * Key decisions based on playwright.dev/docs/best-practices:
 * - fullyParallel: true
 * - CI-aware retries (2 on CI, 0 locally)
 * - forbidOnly on CI
 * - workers: 1 on CI for stability
 * - trace: 'on-first-retry' for debugging
 * - reporter: 'html'
 * - Single browser project from IR environment
 */
export function buildPlaywrightConfig(plan: ExecutionIRPlan): GeneratedFile {
  const env = plan.environment;
  const browserConfig = mapBrowser(env.browser);

  const lines: string[] = [
    "import { defineConfig, devices } from '@playwright/test';",
    '',
    '/**',
    ` * Playwright configuration for ${escapeCommentText(plan.title)}.`,
    ' * Generated by CmdRunner from the Execution IR.',
    ' */',
    'export default defineConfig({',
    "  testDir: './tests',",
    '  fullyParallel: true,',
    '  forbidOnly: !!process.env.CI,',
    '  retries: process.env.CI ? 2 : 0,',
    '  workers: process.env.CI ? 1 : undefined,',
    "  reporter: 'html',",
    '  use: {',
    `    baseURL: '${escapeString(env.baseUrl)}',`,
    `    viewport: { width: ${env.viewport.width}, height: ${env.viewport.height} },`,
    "    trace: 'on-first-retry',",
    '  },',
    '  projects: [',
    '    {',
    `      name: '${browserConfig.projectName}',`,
    `      use: { ...devices['${browserConfig.deviceName}'] },`,
    '    },',
    '  ],',
    '});',
    '',
  ];

  return { path: 'playwright.config.ts', content: lines.join('\n') };
}

/**
 * Generate tsconfig.json for a Playwright TypeScript project.
 *
 * Uses "node" moduleResolution with "commonjs" module — matching
 * Playwright's own scaffolding output (`npm init playwright@latest`).
 */
export function buildTsConfig(includePages = false): GeneratedFile {
  const include = includePages
    ? ['tests/**/*.ts', 'pages/**/*.ts']
    : ['tests/**/*.ts'];
  const content = JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      moduleResolution: 'node',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      outDir: './test-out',
    },
    include,
  }, null, 2);

  return { path: 'tsconfig.json', content: content + '\n' };
}

/**
 * Generate .gitignore for a Playwright project.
 */
export function buildGitIgnore(): GeneratedFile {
  const content = [
    'node_modules/',
    'test-results/',
    'playwright-report/',
    'playwright/.cache/',
    '',
  ].join('\n');

  return { path: '.gitignore', content };
}

/**
 * Generate the test spec file from the IR plan using the M3 renderer.
 */
export function buildTestSpec(plan: ExecutionIRPlan): GeneratedFile {
  const slug = slugify(plan.title);
  const content = renderTestFile(plan);

  return { path: `tests/${slug}.spec.ts`, content };
}

/**
 * Generate the POM test spec file using the M5 POM renderer.
 */
export function buildPomTestSpec(plan: ExecutionIRPlan): GeneratedFile {
  const slug = slugify(plan.title);
  const content = renderPomTestFile(plan);

  return { path: `tests/${slug}.spec.ts`, content };
}

// ── Browser Mapping ───────────────────────────────────────

interface BrowserConfig {
  /** Playwright project name (e.g., 'chromium', 'firefox'). */
  readonly projectName: string;
  /** Playwright device descriptor name (e.g., 'Desktop Chrome'). */
  readonly deviceName: string;
}

/**
 * Map the IR's browser string to Playwright's project and device names.
 *
 * @throws Error for unsupported browsers — this would indicate an IR gap.
 */
function mapBrowser(browser: IREnvironment['browser']): BrowserConfig {
  switch (browser) {
    case 'chrome':
      return { projectName: 'chromium', deviceName: 'Desktop Chrome' };
    case 'firefox':
      return { projectName: 'firefox', deviceName: 'Desktop Firefox' };
    case 'safari':
      return { projectName: 'webkit', deviceName: 'Desktop Safari' };
    case 'edge':
      return { projectName: 'msedge', deviceName: 'Desktop Edge' };
    default:
      throw new Error(
        `Unsupported browser "${browser}" in IR environment. ` +
        `Expected: chrome | firefox | safari | edge.`,
      );
  }
}

// ── Helpers ───────────────────────────────────────────────

/**
 * Slugify a test case title into a valid kebab-case filename.
 * "Login Flow" → "login-flow"
 * "User Registration" → "user-registration"
 */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Escape text for safe embedding in a JSDoc comment block.
// Prevents premature comment termination from star-slash sequences.
function escapeCommentText(text: string): string {
  return text.replace(/\*\//g, '*\\/').replace(/\/\*/g, '\\/\\*');
}

/**
 * Escape a string for safe embedding in single-quoted code.
 * Same escaping logic as all other renderers.
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}
