/**
 * Locator Ranking Tests — Phase 11 Milestone 11.1
 *
 * Tests the shared locator ranking logic extracted from resolveLocatorsForIR().
 * Verifies that both recording-time and execution-time paths produce identical
 * ranking results for the same candidates.
 */

import { describe, it, expect } from 'vitest';
import {
  rankLocatorCandidates,
  filterValidCandidates,
  extractCandidatesFromIdentity,
  isAutoGeneratedId,
  isCssInJsClass,
  LocatorCategory,
  type LocatorCandidate,
} from '../src/domain/locator-ranking';
import { LocatorStrategyType } from '../src/domain/enums';
import type { ElementIdentity } from '../src/shared/types';

// ── Helpers ──────────────────────────────────────────────────

function makeIdentity(overrides: Partial<ElementIdentity> = {}): ElementIdentity {
  return {
    accessibleName: 'Submit',
    ariaRole: 'button',
    ariaLabel: null,
    ariaLabelledBy: null,
    placeholder: null,
    tag: 'BUTTON',
    className: 'btn btn-primary',
    name: null,
    stableId: null,
    testId: null,
    dataCy: null,
    dataQa: null,
    cssSelector: 'button.btn-primary',
    xPath: '/html/body/div/button',
    inIframe: false,
    shadowDom: false,
    elementId: 'elem-0001',
    ...overrides,
  };
}

// ── Auto-Generated ID Detection ──────────────────────────────

describe('isAutoGeneratedId', () => {
  it('detects React auto-generated IDs', () => {
    expect(isAutoGeneratedId('react-123')).toBe(true);
    expect(isAutoGeneratedId('react-1.2.3')).toBe(true);
  });

  it('detects MUI auto-generated IDs', () => {
    expect(isAutoGeneratedId('mui-42')).toBe(true);
  });

  it('detects styled-components IDs', () => {
    expect(isAutoGeneratedId('sc-abc123')).toBe(true);
    expect(isAutoGeneratedId('css-abc123')).toBe(true);
  });

  it('detects Angular auto-generated IDs', () => {
    expect(isAutoGeneratedId('ng-xyz')).toBe(true);
    expect(isAutoGeneratedId('cdk-overlay-1')).toBe(true);
  });

  it('detects hex hash IDs (16+ chars)', () => {
    expect(isAutoGeneratedId('a1b2c3d4e5f6a7b8')).toBe(true);
  });

  it('does NOT flag stable business IDs', () => {
    expect(isAutoGeneratedId('submit-button')).toBe(false);
    expect(isAutoGeneratedId('email-input')).toBe(false);
    expect(isAutoGeneratedId('login-form')).toBe(false);
  });

  it('does NOT flag empty or short values', () => {
    expect(isAutoGeneratedId('')).toBe(false);
    expect(isAutoGeneratedId('btn')).toBe(false);
  });
});

// ── CSS-in-JS Detection ──────────────────────────────────────

describe('isCssInJsClass', () => {
  it('detects styled-components classes', () => {
    expect(isCssInJsClass('.sc-abc123')).toBe(true);
  });

  it('detects emotion classes', () => {
    expect(isCssInJsClass('.emotion-xyz')).toBe(true);
  });

  it('does NOT flag stable CSS classes', () => {
    expect(isCssInJsClass('.btn-primary')).toBe(false);
    expect(isCssInJsClass('.form-control')).toBe(false);
  });
});

// ── filterValidCandidates ────────────────────────────────────

describe('filterValidCandidates', () => {
  it('removes empty values', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: '', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.CSS, value: '  ', category: LocatorCategory.STRUCTURAL },
    ];
    expect(filterValidCandidates(candidates)).toHaveLength(0);
  });

  it('removes auto-generated ID-based CSS selectors', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.CSS, value: '#react-123', category: LocatorCategory.STABLE_TECHNICAL },
      { type: LocatorStrategyType.CSS, value: '#submit-btn', category: LocatorCategory.STABLE_TECHNICAL },
    ];
    const filtered = filterValidCandidates(candidates);
    expect(filtered).toHaveLength(1);
    expect(filtered[0].value).toBe('#submit-btn');
  });

  it('removes CSS-in-JS class selectors', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.CSS, value: '.sc-abc123', category: LocatorCategory.STRUCTURAL },
      { type: LocatorStrategyType.CSS, value: '.btn-primary', category: LocatorCategory.STRUCTURAL },
    ];
    const filtered = filterValidCandidates(candidates);
    expect(filtered).toHaveLength(1);
    expect(filtered[0].value).toBe('.btn-primary');
  });

  it('keeps valid candidates unchanged', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: 'submit-btn', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.ACCESSIBLE_NAME, value: 'Submit', category: LocatorCategory.ACCESSIBILITY },
    ];
    expect(filterValidCandidates(candidates)).toHaveLength(2);
  });
});

// ── rankLocatorCandidates ────────────────────────────────────

describe('rankLocatorCandidates', () => {
  it('ranks business identifiers first', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.CSS, value: '.btn', category: LocatorCategory.STRUCTURAL },
      { type: LocatorStrategyType.TEST_ID, value: 'submit-btn', category: LocatorCategory.BUSINESS },
    ];
    const ranked = rankLocatorCandidates(candidates);
    expect(ranked[0].type).toBe(LocatorStrategyType.TEST_ID);
    expect(ranked[0].priority).toBe(1);
    expect(ranked[0].confidence).toBe(0.90);
  });

  it('ranks accessibility before structural', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.XPATH, value: '/html/body/button', category: LocatorCategory.STRUCTURAL },
      { type: LocatorStrategyType.ACCESSIBLE_NAME, value: 'Submit', category: LocatorCategory.ACCESSIBILITY },
    ];
    const ranked = rankLocatorCandidates(candidates);
    expect(ranked[0].type).toBe(LocatorStrategyType.ACCESSIBLE_NAME);
    expect(ranked[1].type).toBe(LocatorStrategyType.XPATH);
  });

  it('caps at max 3 locators', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: 'a', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.TEST_ID, value: 'b', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.ACCESSIBLE_NAME, value: 'c', category: LocatorCategory.ACCESSIBILITY },
      { type: LocatorStrategyType.CSS, value: '.d', category: LocatorCategory.STABLE_TECHNICAL },
      { type: LocatorStrategyType.XPATH, value: '/e', category: LocatorCategory.STRUCTURAL },
    ];
    const ranked = rankLocatorCandidates(candidates, 3);
    expect(ranked).toHaveLength(3);
  });

  it('deduplicates by type+value', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: 'submit', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.TEST_ID, value: 'submit', category: LocatorCategory.BUSINESS },
    ];
    const ranked = rankLocatorCandidates(candidates);
    expect(ranked).toHaveLength(1);
  });

  it('assigns sequential priorities starting at 1', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: 'a', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.ACCESSIBLE_NAME, value: 'b', category: LocatorCategory.ACCESSIBILITY },
      { type: LocatorStrategyType.CSS, value: '.c', category: LocatorCategory.STRUCTURAL },
    ];
    const ranked = rankLocatorCandidates(candidates);
    expect(ranked.map((r) => r.priority)).toEqual([1, 2, 3]);
  });

  it('returns empty array for no valid candidates', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.CSS, value: '', category: LocatorCategory.STRUCTURAL },
    ];
    expect(rankLocatorCandidates(candidates)).toHaveLength(0);
  });

  it('handles single candidate', () => {
    const candidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: 'submit', category: LocatorCategory.BUSINESS },
    ];
    const ranked = rankLocatorCandidates(candidates);
    expect(ranked).toHaveLength(1);
    expect(ranked[0].priority).toBe(1);
    expect(ranked[0].confidence).toBe(0.90);
  });
});

// ── extractCandidatesFromIdentity ────────────────────────────

describe('extractCandidatesFromIdentity', () => {
  it('extracts testId as business category', () => {
    const identity = makeIdentity({ testId: 'submit-btn' });
    const candidates = extractCandidatesFromIdentity(identity);
    const testIdCandidate = candidates.find((c) => c.type === LocatorStrategyType.TEST_ID);
    expect(testIdCandidate).toBeDefined();
    expect(testIdCandidate!.value).toBe('submit-btn');
    expect(testIdCandidate!.category).toBe(LocatorCategory.BUSINESS);
  });

  it('extracts ariaLabel as accessibility category', () => {
    const identity = makeIdentity({ ariaLabel: 'Submit Form' });
    const candidates = extractCandidatesFromIdentity(identity);
    const ariaCandidate = candidates.find(
      (c) => c.type === LocatorStrategyType.ACCESSIBLE_NAME && c.value === 'Submit Form',
    );
    expect(ariaCandidate).toBeDefined();
    expect(ariaCandidate!.category).toBe(LocatorCategory.ACCESSIBILITY);
  });

  it('extracts stableId as stable technical category', () => {
    const identity = makeIdentity({ stableId: 'submit-btn' });
    const candidates = extractCandidatesFromIdentity(identity);
    const idCandidate = candidates.find(
      (c) => c.type === LocatorStrategyType.CSS && c.value === '#submit-btn',
    );
    expect(idCandidate).toBeDefined();
    expect(idCandidate!.category).toBe(LocatorCategory.STABLE_TECHNICAL);
  });

  it('extracts accessibleName as content category', () => {
    const identity = makeIdentity({ accessibleName: 'Submit' });
    const candidates = extractCandidatesFromIdentity(identity);
    const nameCandidate = candidates.find(
      (c) => c.type === LocatorStrategyType.ACCESSIBLE_NAME && c.value === 'Submit',
    );
    expect(nameCandidate).toBeDefined();
    expect(nameCandidate!.category).toBe(LocatorCategory.CONTENT);
  });

  it('extracts xPath as structural category', () => {
    const identity = makeIdentity();
    const candidates = extractCandidatesFromIdentity(identity);
    const xpathCandidate = candidates.find((c) => c.type === LocatorStrategyType.XPATH);
    expect(xpathCandidate).toBeDefined();
    expect(xpathCandidate!.category).toBe(LocatorCategory.STRUCTURAL);
  });

  it('produces correct priority order when ranked', () => {
    const identity = makeIdentity({
      testId: 'submit',
      ariaLabel: 'Submit',
      accessibleName: 'Submit',
      cssSelector: 'button.btn',
      xPath: '/html/body/button',
    });
    const candidates = extractCandidatesFromIdentity(identity);
    const ranked = rankLocatorCandidates(candidates);

    // Should be: TEST_ID (business) → ROLE (accessibility, from ariaLabel) → ACCESSIBLE_NAME (accessibility)
    // Note: ariaLabel now generates a ROLE candidate (getByRole) at accessibility priority,
    // followed by an ACCESSIBLE_NAME fallback at the same priority.
    expect(ranked[0].type).toBe(LocatorStrategyType.TEST_ID);
    expect(ranked[1].type).toBe(LocatorStrategyType.ROLE);
    expect(ranked[2].type).toBe(LocatorStrategyType.ACCESSIBLE_NAME);
  });
});

// ── Cross-path consistency ───────────────────────────────────

describe('Cross-path consistency', () => {
  it('produces same ranking for equivalent candidates from different sources', () => {
    // Recording-time: candidates extracted from ElementIdentity
    const identity = makeIdentity({
      testId: 'submit',
      ariaLabel: 'Submit Form',
      ariaRole: 'button',
    });
    const recordingCandidates = extractCandidatesFromIdentity(identity);
    const recordingRanked = rankLocatorCandidates(recordingCandidates);

    // Execution-time: same candidates gathered from live DOM
    // Must match the same candidates the identity extractor produces
    // Note: ariaLabel now generates ROLE + ACCESSIBLE_NAME candidates
    const executionCandidates: LocatorCandidate[] = [
      { type: LocatorStrategyType.TEST_ID, value: 'submit', category: LocatorCategory.BUSINESS },
      { type: LocatorStrategyType.ROLE, value: 'button[name="Submit Form"]', category: LocatorCategory.ACCESSIBILITY },
      { type: LocatorStrategyType.ACCESSIBLE_NAME, value: 'Submit Form', category: LocatorCategory.ACCESSIBILITY },
    ];
    const executionRanked = rankLocatorCandidates(executionCandidates);

    // Both should produce identical rankings
    expect(executionRanked).toEqual(recordingRanked);
  });
});
