/**
 * Pipeline V2 — Canonical Event Schema
 *
 * This is the SINGLE shared event schema that every layer of the pipeline uses.
 * No layer may reinterpret, rename, or add fields outside this type.
 *
 * LEARNING 1 (Event Schema Mismatch): The previous implementation failed because
 * the content script sent element info under one field name while the pipeline
 * expected it under another. This file is the canonical contract — if a field
 * name changes, it changes HERE and the TypeScript compiler enforces it everywhere.
 *
 * LEARNING 2 (Event Vocabulary Mismatch): The previous implementation silently
 * dropped events whose type the pipeline didn't recognize. The RecordedEventType
 * enum is a CLOSED vocabulary. Every consumer uses an exhaustive switch over it,
 * so an unrecognized event type is a COMPILE ERROR, not a silent runtime drop.
 */

import type { ElementIdentity } from '../../shared/types';

// Re-export ElementIdentity for convenience
export type { ElementIdentity };

// ════════════════════════════════════════════════════════════════════════
// EVENT VOCABULARY — Closed Set
// ════════════════════════════════════════════════════════════════════════

/**
 * The complete vocabulary of DOM events the V2 Event Observer can produce.
 *
 * This is a CLOSED set. Adding a new type requires:
 *   1. Adding it here
 *   2. Adding a producer in the V2 Event Observer
 *   3. Handling it in every exhaustive switch (compiler-enforced)
 *
 * LEARNING 4 (Missing Event Producers): Every type here MUST have a real
 * producer in the content script. If it doesn't, the exhaustive switch
 * in BoundaryDetector will flag it at compile time.
 */
export const RECORDED_EVENT_TYPES = [
  'click',           // Mouse click on an element
  'dblclick',        // Double click
  'change',          // Form control value committed (select, input blur)
  'input',           // Form control value changing (typing)
  'focus',           // Element received focus
  'blur',            // Element lost focus
  'keydown',         // Keyboard key pressed
  'mouseenter',      // Mouse entered element bounds
  'mouseleave',      // Mouse left element bounds
  'submit',          // Form submitted
  'navigation',      // URL changed (webNavigation API)
  'surface_open',    // A surface appeared (modal, dropdown, menu, popover)
  'surface_close',   // A surface disappeared
  'scroll',          // Scroll position changed (throttled)
] as const;

export type RecordedEventType = (typeof RECORDED_EVENT_TYPES)[number];

/**
 * Type guard: is this string a valid RecordedEventType?
 * Use this at message boundaries to validate incoming events.
 */
export function isRecordedEventType(value: string): value is RecordedEventType {
  return (RECORDED_EVENT_TYPES as readonly string[]).includes(value);
}

// ════════════════════════════════════════════════════════════════════════
// CANONICAL EVENT — Shared by Every Layer
// ════════════════════════════════════════════════════════════════════════

/**
 * The canonical event that flows through the entire pipeline.
 *
 * PRODUCED BY: V2 Event Observer (content script)
 * CONSUMED BY: BoundaryDetector → StateDiffEngine → PatternRegistry →
 *              InteractionAssembler → IntentResolver
 *
 * Every field name in this interface is the CONTRACT. No layer may:
 *   - Read element info from a different field name
 *   - Expect a field that isn't declared here
 *   - Silently drop an event because it "doesn't have the right shape"
 *
 * The `element` field carries the full ElementIdentity. This is non-optional
 * for all events except navigation (where there is no element).
 *
 * LEARNING 7 (collectIdentity): The element identity MUST be fully populated
 * by the content script. The V2 Event Observer populates every field of
 * ElementIdentity — accessibleName, ariaRole, tag, type, ariaAttributes, etc.
 * No layer needs to re-extract identity from a raw DOM element.
 */
export interface PipelineEvent {
  /** Unique event ID (generated by the observer, used for tracing). */
  readonly eventId: string;

  /** The event type from the closed vocabulary. */
  readonly type: RecordedEventType;

  /** ISO timestamp when the event was captured. */
  readonly timestamp: string;

  /** Full element identity. Null only for navigation events. */
  readonly element: ElementIdentity | null;

  /** The DOM event target's tag name (e.g. 'BUTTON', 'INPUT', 'SELECT'). */
  readonly targetTag: string | null;

  /**
   * Event-specific payload. Type-narrowed via the eventType field.
   * Every event type documents what fields it carries here.
   */
  readonly payload: EventPayload;

  /** Whether the event is trusted (user-initiated) vs synthetic. */
  readonly isTrusted: boolean;
}

/**
 * Event-specific payload, discriminated by event type.
 *
 * Each event type carries different information in its payload.
 * Consumers narrow on `event.type` to access the right payload shape.
 */
export interface EventPayload {
  // ── Click / Double-click ──
  /** Click count (1 for click, 2 for dblclick). Present for click/dblclick. */
  clickCount?: number;

  /** Mouse button (0=left, 1=middle, 2=right). Present for click/dblclick. */
  button?: number;

  /** Keyboard modifiers active during the event. */
  modifiers?: EventModifiers;

  // ── Input / Change ──
  /** The current value of the input/select/textarea. Present for input/change. */
  value?: string;

  /** The previous value (if known). Present for input/change. */
  previousValue?: string;

  /** Checked state for checkbox/radio inputs. Present for input/change. */
  checked?: boolean;

  // ── Keydown ──
  /** The key pressed (e.g. 'Enter', 'Escape', 'Tab'). Present for keydown. */
  key?: string;

  /** The key code (e.g. 'Enter', 'Escape'). Present for keydown. */
  code?: string;

  // ── Navigation ──
  /** New URL. Present for navigation. */
  url?: string;

  /** Page title. Present for navigation. */
  title?: string;

  // ── Surface Open / Close ──
  /** Surface type. Present for surface_open/surface_close. */
  surfaceType?: SurfaceType;

  /**
   * Descriptor of the surface element that opened or closed.
   * Present for surface_open/surface_close.
   */
  surfaceElement?: ElementDescriptor;

  // ── Submit ──
  /** The form's accessible name or action URL. Present for submit. */
  formAction?: string;

  // ── Scroll ──
  /** Scroll X position. Present for scroll. */
  scrollX?: number;

  /** Scroll Y position. Present for scroll. */
  scrollY?: number;

  // ── State Snapshot ──
  /**
   * A state snapshot captured by the content script at the time of this event.
   * The Pipeline V2 orchestrator (running in the service worker) cannot access
   * the DOM, so the content script captures snapshots and embeds them here.
   * The orchestrator uses the first event's snapshot as "before" and the last
   * event's snapshot as "after" for each interaction unit.
   */
  stateSnapshot?: unknown;
}

/**
 * The type of overlay surface that appeared or disappeared.
 */
export type SurfaceType = 'modal' | 'dropdown' | 'menu' | 'popover' | 'dialog';

/**
 * A lightweight descriptor for an element that appeared or disappeared.
 * Used by surface_open/surface_close events and state snapshots.
 */
export interface ElementDescriptor {
  /** Accessible name of the element. */
  accessibleName: string;
  /** ARIA role. */
  ariaRole: string | null;
  /** Tag name. */
  tag: string;
  /** Element ID (for DOM lookup). */
  id: string | null;
  /** CSS selector (for replay). */
  cssSelector: string;
}

/**
 * Keyboard modifier state during an event.
 */
export interface EventModifiers {
  ctrlKey: boolean;
  altKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
}

// ════════════════════════════════════════════════════════════════════════
// INTERACTION UNIT — Boundary-Detected Grouping
// ════════════════════════════════════════════════════════════════════════

/**
 * A group of PipelineEvents that form one atomic user interaction.
 *
 * Example: clicking a dropdown trigger, then clicking an option = 1 unit.
 * The boundary detector groups these by:
 *   - Surface lifecycle (open → interact → close)
 *   - Temporal proximity (events within GAP_MS of each other)
 *   - Focus continuity (focus on related elements)
 *
 * PRODUCED BY: BoundaryDetector
 * CONSUMED BY: StateDiffEngine, PatternRegistry, InteractionAssembler
 */
export interface InteractionUnit {
  /** Unique unit ID. */
  readonly unitId: string;

  /** All events in this interaction, in chronological order. */
  readonly events: PipelineEvent[];

  /** The primary event (the one that likely initiated the interaction). */
  readonly primaryEvent: PipelineEvent;

  /** Start timestamp (first event). */
  readonly startTime: string;

  /** End timestamp (last event). */
  readonly endTime: string;

  /**
   * How this unit's boundary was determined.
   * Useful for debugging and traceability.
   */
  readonly boundaryReason: BoundaryReason;
}

/**
 * Why the boundary detector closed an interaction unit.
 */
export type BoundaryReason =
  | 'surface_closed'     // A surface that was open has now closed
  | 'temporal_gap'       // No events for TEMPORAL_GAP_MS
  | 'focus_lost'         // Focus moved to an unrelated element
  | 'navigation'         // URL changed
  | 'explicit_flush';    // flush() called (e.g. Stop Recording)

// ════════════════════════════════════════════════════════════════════════
// STATE SNAPSHOT + STATE DIFF
// ════════════════════════════════════════════════════════════════════════

/**
 * A complete snapshot of observable DOM state at a point in time.
 *
 * PRODUCED BY: StateDiffEngine (before and after each interaction unit)
 */
export interface StateSnapshot {
  readonly timestamp: string;
  readonly url: string;
  readonly pageTitle: string;

  // ── Form State ──
  readonly inputs: InputFieldState[];
  readonly checkboxes: ToggleState[];
  readonly radios: RadioGroupState[];
  readonly toggles: ToggleState[];
  readonly ranges: RangeState[];

  // ── Focus State ──
  readonly focusedElement: ElementDescriptor | null;

  // ── Structural State ──
  readonly openSurfaces: OpenSurfaceState[];
  readonly activeTab: TabState | null;
  readonly expandedAccordions: ElementDescriptor[];

  // ── DOM Structural State ──
  /** Count of visible interactive elements (for structural change detection). */
  readonly interactiveElementCount: number;
}

export interface InputFieldState {
  readonly descriptor: ElementDescriptor;
  readonly value: string;
  readonly inputType: string;
}

export interface ToggleState {
  readonly descriptor: ElementDescriptor;
  readonly checked: boolean;
}

export interface RadioGroupState {
  readonly name: string;
  readonly descriptor: ElementDescriptor;
  readonly selectedOption: ElementDescriptor | null;
  readonly options: ElementDescriptor[];
}

export interface RangeState {
  readonly descriptor: ElementDescriptor;
  readonly value: string;
  readonly min: string;
  readonly max: string;
}

export interface OpenSurfaceState {
  readonly type: SurfaceType;
  readonly descriptor: ElementDescriptor;
}

export interface TabState {
  readonly selectedTab: ElementDescriptor;
  readonly activePanel: ElementDescriptor;
}

/**
 * The structured difference between two StateSnapshots.
 *
 * This is the PRIMARY SIGNAL for intent resolution. The Intent Resolver
 * consults the StateDiff first; patterns are accelerators.
 *
 * PRODUCED BY: StateDiffEngine
 * CONSUMED BY: PatternRegistry, InteractionAssembler, IntentResolver
 */
export interface StateDiff {
  readonly valueChanges: ValueChange[];
  readonly toggleChanges: ToggleChange[];
  readonly radioChanges: RadioChange[];
  readonly rangeChanges: RangeChange[];
  readonly focusChange: FocusChange | null;
  readonly surfaceChanges: SurfaceChange[];
  readonly tabChange: TabChange | null;
  readonly urlChange: UrlChange | null;
  readonly structuralChangeDetected: boolean;
}

export interface ValueChange {
  readonly descriptor: ElementDescriptor;
  readonly field: string;
  readonly before: string;
  readonly after: string;
  readonly inputType: string;
}

export interface ToggleChange {
  readonly descriptor: ElementDescriptor;
  readonly field: string;
  readonly before: boolean;
  readonly after: boolean;
}

export interface RadioChange {
  readonly groupName: string;
  readonly groupDescriptor: ElementDescriptor;
  readonly before: ElementDescriptor | null;
  readonly after: ElementDescriptor | null;
}

export interface RangeChange {
  readonly descriptor: ElementDescriptor;
  readonly field: string;
  readonly before: string;
  readonly after: string;
}

export interface FocusChange {
  readonly from: ElementDescriptor | null;
  readonly to: ElementDescriptor | null;
}

export interface SurfaceChange {
  readonly type: SurfaceType;
  readonly action: 'opened' | 'closed';
  readonly descriptor: ElementDescriptor;
}

export interface TabChange {
  readonly from: ElementDescriptor;
  readonly to: ElementDescriptor;
}

export interface UrlChange {
  readonly from: string;
  readonly to: string;
}

// ════════════════════════════════════════════════════════════════════════
// PATTERN MATCH
// ════════════════════════════════════════════════════════════════════════

/**
 * The result of matching an interaction unit against the Pattern Registry.
 *
 * The Pattern Registry contains ~12 GENERIC interaction behaviors (not
 * framework-specific component patterns). A match is an accelerator:
 * it speeds up resolution and increases confidence, but it is NOT required.
 * The Intent Resolver produces a business action from the StateDiff alone
 * even when no pattern matches.
 *
 * PRODUCED BY: PatternRegistry
 * CONSUMED BY: InteractionAssembler, IntentResolver
 */
export interface PatternMatch {
  /** The generic behavior that matched (e.g. 'single-selection-from-set'). */
  readonly behavior: InteractionBehavior;

  /** Confidence that this pattern correctly describes the interaction. */
  readonly confidence: number;

  /** Human-readable rationale for why this pattern matched. */
  readonly rationale: string;

  /** Pattern-specific metadata extracted during matching. */
  readonly metadata: PatternMetadata;
}

/**
 * The generic interaction behaviors the Pattern Registry recognizes.
 *
 * These represent fundamental user intentions, NOT UI component types.
 * 'single-selection-from-set' covers native <select>, Material UI Select,
 * Ant Design Select, Radix Select, radio groups, and custom dropdowns —
 * because they all produce the same observable behavior.
 */
export type InteractionBehavior =
  | 'single-selection-from-set'  // Pick one option from a group
  | 'multi-selection-from-set'   // Pick multiple options
  | 'boolean-toggle'             // Flip a yes/no state
  | 'text-entry-commit'          // Enter or modify text
  | 'date-time-selection'        // Pick a date/time
  | 'expand-collapse'            // Open/close a section
  | 'context-switch'             // Move between views (tabs)
  | 'navigation'                 // Move to a new URL
  | 'hover-intent'               // Hover to reveal content
  | 'simple-click'               // Click with no complex state change
  | 'form-submit'                // Submit a form
  | 'generic-fallback';          // Unknown control — state diff only

/**
 * Pattern-specific metadata extracted during matching.
 * Different behaviors populate different fields.
 */
export interface PatternMetadata {
  /** Selected value (for selection behaviors). */
  readonly selectedValue?: string;
  /** Previous value (for selection behaviors). */
  readonly previousValue?: string;
  /** Selected option descriptor (for selection behaviors). */
  readonly selectedOption?: ElementDescriptor;
  /** Entered text value (for text-entry). */
  readonly textValue?: string;
  /** Toggle state (for boolean-toggle). */
  readonly toggleState?: boolean;
  /** Date display value (for date-time-selection). */
  readonly dateValue?: string;
  /** ISO date value (for date-time-selection). */
  readonly dateIsoValue?: string;
  /** Surface type (for expand-collapse). */
  readonly surfaceType?: SurfaceType;
  /** Input type of the changed element (for single-selection). */
  readonly inputType?: string;
}

// ════════════════════════════════════════════════════════════════════════
// RESOLVED ACTION — Intent Resolver Output
// ════════════════════════════════════════════════════════════════════════

/**
 * The final resolved business action.
 *
 * The Intent Resolver ALWAYS produces one of these, even for unknown controls.
 * For unrecognized controls, it uses the 'generic-fallback' behavior and
 * resolves from the StateDiff alone, with LOW confidence.
 *
 * PRODUCED BY: IntentResolver
 * CONSUMED BY: PipelineV2.toSessionEvent()
 */
export interface ResolvedAction {
  /** The resolved interaction behavior. */
  readonly behavior: InteractionBehavior;

  /** The SessionEvent type this action maps to. */
  readonly sessionEventType: SessionEventType;

  /** Confidence in the resolution (0.0 to 1.0). */
  readonly confidence: number;

  /** The element identity for the SessionEvent. */
  readonly elementIdentity: ElementIdentity | null;

  /** Type-specific fields for the SessionEvent. */
  readonly fields: ResolvedActionFields;

  /** Human-readable description of the resolved action. */
  readonly description: string;

  /** Why the resolver chose this action (for tracing). */
  readonly rationale: string;
}

/**
 * The SessionEvent type values (matches shared/types.ts union).
 */
export type SessionEventType =
  | 'navigation'
  | 'click'
  | 'text'
  | 'hover'
  | 'checkbox'
  | 'radio'
  | 'select'
  | 'dateSelect';

/**
 * Type-specific fields carried on the resolved action.
 * These map directly to SessionEvent variant fields.
 */
export interface ResolvedActionFields {
  readonly value?: string;
  readonly checked?: boolean;
  readonly dateType?: string;
  readonly displayValue?: string;
  readonly isoValue?: string;
  readonly url?: string;
  readonly title?: string;
}

// ════════════════════════════════════════════════════════════════════════
// TRACE — Runtime Traceability
// ════════════════════════════════════════════════════════════════════════

/**
 * A single trace entry showing an event's journey through one pipeline layer.
 *
 * LEARNING 5 (Runtime Traceability): The previous implementation had no way
 * to debug the flow. This trace system makes every event's path through
 * the pipeline visible.
 *
 * PRODUCED BY: PipelineTracer (called by each layer)
 * VISIBLE IN: DevTools console + side panel trace view
 */
export interface TraceEntry {
  readonly timestamp: string;
  readonly layer: TraceLayer;
  readonly eventId?: string;
  readonly unitId?: string;
  readonly action: string;
  readonly input: string;
  readonly output: string;
  readonly durationMs: number;
  readonly decision?: string;
}

export type TraceLayer =
  | 'event-capture'
  | 'boundary-detection'
  | 'state-diff'
  | 'pattern-registry'
  | 'interaction-assembler'
  | 'intent-resolver'
  | 'pipeline-output';

/**
 * Trace level controls verbosity.
 */
export type TraceLevel = 'off' | 'errors-only' | 'normal' | 'verbose';
